### ISSUE TITLE
Rucio / FTS make two requests for multihop functionality

### ISSUE THREAD

**Issue by KatyEllis** [dmwm/CMSRucio#114]
Hi, I understand that the intended behaviour is that multihop creates only 1 FTS job for the entire transfer, e.g. SiteX -> CERN EOS disk -> CERN CTA tape.

This is not the case. In my testing for CMS I can see clearly in the Rucio conveyor-submitter log that 2 FTS jobs are submitted immediately when I create a Rucio rule. One transfer for SiteX->EOS and another for EOS->CTA. Usually the first one succeeds, but the second fails as the file is not yet available at the source.

To see an example, check out FTS IDs
493a70f2-6969-11ea-a092-02163e018125
49492eda-6969-11ea-add7-02163e00f0f3

on [https://fts3-pilot.cern.ch:8449/fts3/ftsmon/#/]

A short time later a third job appears and the file is transferred successfully:
a83667f0-6969-11ea-9963-02163e00f0f3

The overall outcome is correct, but this is going to have a big effect on the 'efficiency' of the service, as no more than half of all FTS requests to CTA can succeed. 

For the reverse transfer CTA -> EOS -> SiteX I can only presume that the number of failed jobs will be even longer due to the unknown tape staging time.

**Comment by ericvaandering** [comment]
Hey Katy,

This GitHub is just our happy little band. Rucio/rucio is the full team. Regardless I brought this up at the meeting today and they are surprised but Cedric will look into it.

**Comment by KatyEllis** [comment]
Darn. I did look for a ‘create issue’ button on the main Rucio github but I did not see one, even though I appeared to be signed in. It think it was because I was doing a search. I’m on the correct page now and found ‘new issue’.

I sent Martin the link to the Issue earlier. Should I copy over to a Rucio/rucio issue instead?

Katy

**Comment by KatyEllis** [comment]
Issue created in the wrong place. Created issue https://github.com/rucio/rucio/issues/3398 instead and closing this.
