### ISSUE TITLE
"ERROR	Data identifier not found." Rule for transferring a particular dataset is not correctly processed

### ISSUE THREAD

**Issue by dpiparo** [dmwm/CMSRucio#135]
Dear devels and operators,

bear with me: I am a beginner with Rucio!

Adding rules to schedule transfers on personal T2 space in general works quite well but I stumbled in a strange behaviour today. Once trying this command
```
rucio add-rule cms:/SingleMuon/CMSSW_11_0_0_pre10-110X_dataRun2_PromptLike_v6_nanov6-v1/NANOAOD  1 T2_CH_CERN
```
this error was prompted
```
2020-05-19 13:37:31,018	ERROR	Data identifier not found.
Details: Data identifier cms:/SingleMuon/CMSSW_11_0_0_pre10-110X_dataRun2_PromptLike_v6_nanov6-v1/NANOAOD is not valid.
```
Even if for DAS the dataset is OK: https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FSingleMuon%2FCMSSW_11_0_0_pre10-110X_dataRun2_PromptLike_v6_nanov6-v1%2FNANOAOD even if the source seems to be only in phedex.

Cheers,
    Danilo

**Comment by dynamic-entropy** [comment]
Hi Danilo, 
Closing it since it's too old and would work now.
Most probably at that time, the DID was still not registered in Rucio and hence the error.
Additionally if DAS was already using Rucio as a source, then "PhedEx" being shown as the only source explains it.
