### ISSUE TITLE
Rucio source check if cmsos command available

### ISSUE THREAD

**Issue by juztas** [dmwm/CMSRucio#233]
It would be nice if Rucio checks if cmos command available and if not - raise an error (either point to TWiki or ask to source cmsset_default.sh)
```
-bash-4.2$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
-bash: cmsos: command not found
Error: Unable to find rucio version 'current'
-bash-4.2$ source /cvmfs/cms.cern.ch/cmsset_default.sh
-bash-4.2$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
```

**Comment by ericvaandering** [comment]
I think you want to open this against cmssw: https://github.com/cms-sw/cmsdist

The setup script is their responsibility.
