### ISSUE TITLE
Investigate Rucio Oracle performance issues with help of CERN DBA:

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#259]
Met with CERN DBA and RUCIO project leader regarding CMS Rucio DB.

**Comment by yuyiguo** [comment]
@kdziedzi@cern.ch @ericvaandering 
Eric, Kate is not in CMS github , can she receive this notification ?
Hi Kate,
Just back from my vacation. The day before I was leaving, we talked about generating DB status comparing the deletion camping and normal running in private chat. Can you upload the report to this issue so both Eric and I  can look into it?

**Comment by yuyiguo** [comment]
Try to upload DB stats during the May 18 3 m to May 18 10 am CERN time while the deletion campaign.  But github does not support html files as attachment.

**Comment by ericvaandering** [comment]
Should we close this?
