### ISSUE TITLE
Deploy auth server with OIDC authN on integration cluster

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#261]
https://github.com/dmwm/rucio-flux/issues/61

**Comment by dciangot** [comment]
@ericvaandering regarding sync script for OIDC subject <-> rucio account. 

I have a script that can do that and it needs:
- a special IAM ID and secret authorized to get users details
- a rucio account capable of adding identities to accounts

I was thinking that should be quite easy to integrate this with the CRIC sync script, or maybe make a parallel one (even better). What are your thougths/preferences?

**Comment by ericvaandering** [comment]
My suggestion would be another script run by this script: https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/scripts/k8s_sync_users_links.sh <https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/scripts/k8s_sync_users_links.sh>

This runs every 12 hours and runs with the Robot account so no problems with adding identities. 

I assume the secret needed to get user details does not change frequently? Then I would make your script pick it up from an environment variable and I’ll get it into that variable via kubernetes mechanisms

**Comment by dciangot** [comment]
> My suggestion would be another script run by this script: https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/scripts/k8s_sync_users_links.sh <https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/scripts/k8s_sync_users_links.sh> This runs every 12 hours and runs with the Robot account so no problems with adding identities. I assume the secret needed to get user details does not change frequently? Then I would make your script pick it up from an environment variable and I’ll get it into that variable via kubernetes mechanisms

So far I have added a separate .sh that contains the oidc-agent configuration (needed to refresh the token used to get user info). I'd avoid to get x509 sync stuck due to OIDC server issues or any bug related to this. Can we evaluate to setup a separate k8s cronjob?

**Comment by ericvaandering** [comment]
I'd rather not. We can investigate setting timeouts or just do your part at the end.

**Comment by ericvaandering** [comment]
https://stackoverflow.com/questions/55431218/cron-job-with-timeout

I should set these in general.

**Comment by dciangot** [comment]
Ok, np, I'll put all in the same sh then.

**Comment by ericvaandering** [comment]
Then we need something like https://github.com/dmwm/rucio-flux/commit/e583d7e0725733262b1b38fcdf952d8065ab2e6b for prod as well

**Comment by dciangot** [comment]
Created #312 for PROD deployment. I'm closing this.
