### ISSUE TITLE
Sync script to map user token subject to RUCIO account

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#272]
Using SCIM:read IAM credentials retrieve the list of IAM accounts and map them to RUCIO ones

**Comment by dciangot** [comment]
Tested PR #311  on int server with the docker image created by end.

Now every user already in int server should be able to do `rucio whoami`  with the rucio conf in the form of what I put in `docker/CMSRucioClient/examples/rucio-int-oidc.cfg`

**Comment by dciangot** [comment]
@ericvaandering  This is the missing part to be included in flux to unlock #261 and put it into production

**Comment by ericvaandering** [comment]
Fixed a typo in #314

**Comment by ericvaandering** [comment]
Closing
