### ISSUE TITLE
User/site admin dedicated rucio WebUI

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#274]
Can be seen in part as an extension of current one WebUI:
- per did research and listing of all the rules separated by parent level
    - also some monitoring/insight capabilities on the overall locked space at a site
- Per RSE search space overview and (if requested) detailed list of contents grouped by: rules accounts, subscriptions, data tier etc..

Everything possibly online via rucio API, with an eventual cache to be evaluated

First prototype already here: https://cms-monit-temp-cms-monit-test.apptest.cern.ch

Got some more request on the jira monitoring ticket: https://its.cern.ch/jira/browse/CMSMONIT-454

**Comment by dynamic-entropy** [comment]
After some considerations, we are testing a GraphDB approach to answering questions pertaining to data management. With a table / document-based DBs we were often required to maintain a separate table to answer each specific question. We still have that as a backup option if this approach does not pass the functional and performance tests. 

Here is a test deployment of a prototype with very limited data (100 cms datasets/ rucio containers - we are trying to get an instance with all data up soon for more extensive and performance testing), http://r-neo4j.cern.ch:7474/browser/. 

username: `neo4j`
password: `mypass`

Feedback and additional questions that might need answering are welcome: 

Here are a couple of questions we are trying to answer (later we try to present this in the dashboard using appropriate representations). For now, you may copy-paste these commands in the browser. 

1. Visualise the data model
`CALL db.schema.visualization`

2. Amount of data locked by rules
`MATCH (r:Rule)<-[:HAS_RULE]-(d:Dataset) RETURN r.id, r.account, sum(toInteger(d.size)) AS size_locked ORDER BY size_locked DESC`

3. Space used by account at all RSE
`MATCH (account:Account {account: "transfer_ops"})-[cr:CREATED_RULE]->(rule:Rule)
MATCH (dataset:Dataset)-[la:LOCKED_AT {rule_id: rule.id}]-(rse:Rse)
RETURN account.account, rse.rse, SUM(toInteger(dataset.size))`

4. Space used at RSE by account
`MATCH (account:Account)-[cr:CREATED_RULE]->(rule:Rule)
MATCH (dataset:Dataset)-[la:LOCKED_AT {rule_id: rule.id}]-(rse:Rse {id: "89a267a997d74de6850af9442e21d2a8"})
RETURN account.account, SUM(toInteger(dataset.size))`

5. Container at a RSE
`MATCH (c:Container)-[:CONSITS_OF]->(d:Dataset)-[:LOCKED_AT]->(r:Rse {id: "89a267a997d74de6850af9442e21d2a8"})
RETURN c.cname, c.account`

6. Total datasets of Container vs datasets at a RSE
`MATCH (c:Container)-[:CONSITS_OF]->(d:Dataset)-[:LOCKED_AT]->(r:Rse {id: "89a267a997d74de6850af9442e21d2a8"})
MATCH (c)-[:CONSITS_OF]->(od:Dataset)
RETURN c.cname, COUNT(d) AS dataset_at_rse, COUNT(od) AS total_dataset`

**Comment by dynamic-entropy** [comment]
The graph database was not able to perform for a large number of nodes for our query needs. We fall back to daily pyspark jobs and a MongoDB database backend with a FastAPI as our API server.

Spark Analysis Repo: https://github.com/dynamic-entropy/DatasetRuleAnalysis
WebServer Repo: https://github.com/dynamic-entropy/laughing-happiness
Preliminary Table: http://cmsweb-test1-zone-a-woki2wrztp4s-node-0.cern.ch:30017/table

**Comment by dynamic-entropy** [comment]
- [ ] Dataset Rule Table
- [ ] Sub-table with Dataset locations at other RSEs

**Comment by dynamic-entropy** [comment]
Hello @dciangot 

I think we are not going ahead with this. 
If we still want to, I would prefer we give a hand and proposal for the new Rucio UI https://github.com/rucio/webui 
For reasons of maintainability and usefulness. 

Let me know what you think.

**Comment by dciangot** [comment]
Yeah, I'd put this issue in waiting for the new UI tests

**Comment by dynamic-entropy** [comment]
I am closing this. We can wait for the UI without this ticket being open :)
