### ISSUE TITLE
WebService for temporary data staging

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#276]
Useful for oneshot analysis (O(7d)) that does not require a long term replica to be available, but that can benefit from local user dedicated computing resources

The approach is somehow similar to the approach for CRAB tape recall mechanism:
- an account with a fixed amount of quota at T2s
- eventually supporting ask-approval
- fixed limit for rule lifetime (e.g. 7d)

a CLI to interact with the REST API will also be needed, and/or a webService.

The solution should include:

- [ ] check for data already staged on other disk area (in the same region?, everywhere?)
- [ ] check on the size of the requests
- [ ] monitoring of the status/rule id refs

**Comment by dynamic-entropy** [comment]
Document with updated goals: 
https://docs.google.com/document/d/1i-0uGs_wqsLBvrzK3QeHVhe_8vlMIe6gGryoE5gV_dM/edit#

Document for technical discussion: 
https://codimd.web.cern.ch/wNshv8qOR8ippcN70W1i_g

Pyspark Analysis Repo: https://github.com/dynamic-entropy/CRABAnalysis

**Comment by dciangot** [comment]
I'm afraid we need to "re-scope" this issue to something more under DM-ops guidance, both for lack of manpower and for a better time/usefulness ratio. Meaning that we have to target a minimal valuable implementation and push for that.

I'm setting a dedicate document where I'll ask all the player to partecipate and contribute.

**Comment by dciangot** [comment]
Not needed anymore I think, closing and re-opening if needed
