### ISSUE TITLE
Probes Deployment Q2

### ISSUE THREAD

**Issue by FernandoGarzon** [dmwm/CMSRucio#280]
- [x] S/R/U Rules and Locks counts: https://github.com/rucio/probes/pull/98

- [ ] Move probes in /cms/ over to context manager and python3 (Use "with PrometheusPusher")
- Start with /cms/check_free_space
- [x] Get old PRs merged in Repo:
-  https://github.com/rucio/probes/pull/79

**Comment by ericvaandering** [comment]
Mostly done, moving remainder to #305
