### ISSUE TITLE
Move probes in /cms/ over to context manager and python3 (Use "with PrometheusPusher")  

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#305]

**Comment by Panos512** [comment]
I have made a preliminary review of all our probes here https://docs.google.com/spreadsheets/d/1IgMCY8ney08bZ1A_PH-hh2gqMCK5fZmE4WhToz--ArU/edit?usp=sharing

**Comment by ericvaandering** [comment]
Need to merge https://github.com/rucio/probes/pull/122 to really close this off, but https://github.com/rucio/probes/pull/115 needs to go first
