### ISSUE TITLE
Deploy data injection CLI on cvmfs

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#306]
Make CLI available to users and begin preliminary testing
Issue - #275
PR - #282

- [x] Deploy on CVMFS
- [ ] Test using KIT data registration and transfer

**Comment by dciangot** [comment]
@dynamic-entropy as Stefano suggest in https://github.com/dmwm/CRABServer/issues/5986 I propose to add documentation on how to use the scripts (as soon as they will be on cvmfs) on the rucio twiki. 

I have updated the issue description accordingly.

**Comment by dynamic-entropy** [comment]
Refactored code to build with poetry: [PR ](https://github.com/dmwm/CMSRucio/pull/344)
