### ISSUE TITLE
Implement empty dir removal in consistency checks

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#327]
Right now it is possible in Rucio to leave at the RSE a certain number of empty dirs. We can introduce a clean up procedure into the consistency checks that can take care of cleanup dirs older than a certain time interval.

**Comment by ivmfnal** [comment]
The procedure should not remove recently created directories. To prevent that, same logic as with dark files should be used to make sure that the empty directory is old enough to be removed.

**Comment by dynamic-entropy** [comment]
Closing this, it is marked done on the project board and the linked PR is merged.
