### ISSUE TITLE
Implement empty dir removal as part of consistency enforcement

### ISSUE THREAD

**Issue by ivmfnal** [dmwm/CMSRucio#329]

**Comment by ivmfnal** [comment]
See https://github.com/dmwm/CMSRucio/issues/327

**Comment by ivmfnal** [comment]
Put into production on 10/14/2022. Still need to show stats in the monitor

**Comment by ericvaandering** [comment]
Can close, right?

**Comment by ivmfnal** [comment]
Yes

Sent from my iPhone

On Nov 16, 2022, at 11:22 AM, Eric Vaandering ***@***.***> wrote:

﻿

Can close, right?

**Comment by klannon** [comment]
It seems like this should have been closed 2 mo ago, but is still open (though listed as done in the project board.  Can we close the issue?  @ivmfnal @ericvaandering

**Comment by ivmfnal** [comment]
This is implemented and works for ~50% of sites. But for the remaining ~half, it does not work because xrootd interface does not have permission to write. There was a conversation with Stephan Lammel ~ Christmas time where we agreed to revisit this ~March 2023.
So we can close this from technical standpoint, but maybe open new issue as an administrative/operational ?
