### ISSUE TITLE
Update db/sqla SQLAlchemy migration upon  code review by Rucio team. PR #5872 (https://github.com/rucio/rucio/pull/5872)

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#339]
https://github.com/rucio/rucio/pull/5872

**Comment by yuyiguo** [comment]
Thanks, Eric for the ticket. I did not realize that I needed to open this ticket.

**Comment by yuyiguo** [comment]
Got the PR reviewed by a Rucio main developer. Updating the code.

**Comment by yuyiguo** [comment]
PR merged into Rucio's main repo.  All Done.
