### ISSUE TITLE
Too many admin accounts

### ISSUE THREAD

**Issue by nsmith-** [dmwm/CMSRucio#351]
Any account that has the attribute `"admin": True` will bypass all account quotas for rules it makes. Currently the list, excepting `sync_` accounts, is:
```
>>> print("\n".join(row["account"] for row in client.list_accounts(filters={"admin": True}) if not row["account"].startswith("sync_")))
crab_tape_recall
root
tier0_prod
tier0_replay
transfer_ops
wma_logs
wma_prod
wmcore_output
wmcore_transferor
```
Most of these have no need for admin privilege, rather it is a way to sidestep needing to specify fine-grained policy #343.

**Comment by nsmith-** [comment]
In particular, the accounts
```
crab_tape_recall
wmcore_output
wmcore_transferor
```
are the ones where it would be good to set account-level RSE quotas. Though at least for `wmcore_transferor` the MSTransferor service self-polices it's data usage.

**Comment by dynamic-entropy** [comment]
Will follow in #627
