### ISSUE TITLE
fix connection problems in Hermes and Kronos

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/CMSRucio#356]

**Comment by dciangot** [comment]
do we have a plan for this? New int cluster is up, but I had to turn off kronos. It was creating the usual mess, still.

**Comment by yuyiguo** [comment]
I have meetings on Mondays till to 3 pm.  Can we schedule a meeting to discuss this tomorrow ?
From: dciangot ***@***.***>
Date: Monday, April 3, 2023 at 3:01 AM
To: dmwm/CMSRucio ***@***.***>
Cc: Yuyi Guo ***@***.***>, Assign ***@***.***>
Subject: Re: [dmwm/CMSRucio] fix connection problems in Hermes and Kronos (Issue #356)

do we have a plan for this? New int cluster is up, but I had to turn off kronos. It was creating the usual mess, still.

**Comment by yuyiguo** [comment]
Done as Rucio upgrade to 1.31.3.
