### ISSUE TITLE
Username is passed instead of email ids in sync scripts for accounts

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#362]
https://github.com/dmwm/CMSRucio/blob/568849ee4f5c90227c8faabae8dd4bcc602b91a8/docker/CMSRucioClient/scripts/syncRolesToAttributesLocalUsers.py#L87

https://github.com/dmwm/CMSRucio/blob/568849ee4f5c90227c8faabae8dd4bcc602b91a8/docker/CMSRucioClient/scripts/syncRolesToAttributesLocalUsers.py#L116

dn_account_map: maps dn to username but `client.add_identity` requires email. [Rucio docs](http://rucio.cern.ch/documentation/client_api/accountclient#add_identity)

Reproduce / Verify:
```
from rucio.client.client import Client

client = Client()
desy_local = list(client.list_identities('t2_de_desy_local_users'))
for user in desy_local:
    print(user['email'])
```

- [x] Correct to use of email address instead of email
- [ ] Write one-time script to update earlier account identities

@ericvaandering

**Comment by dynamic-entropy** [comment]
The `roles` preset that the script uses did not include the email address of the user. @Panos512 has modified the preset to include the `email` field as well. Many thanks :)

Will try to write a corrective script for the ones that are already added with a username.

**Comment by ericvaandering** [comment]
This is for the normal user accounts?

**Comment by dynamic-entropy** [comment]
The email address associated with the identity is added to the account (in our case the group account) while creating an association.
The type of added identities is (http://rucio.cern.ch/documentation/client_api/accountclient/#add_identity):
`[ {'type': 'X509', 'identity': '<dn>', 'email': 'id'} ]`

**Comment by ericvaandering** [comment]
This issue is a year old. Is it still relevant?

**Comment by dynamic-entropy** [comment]
Hello @ericvaandering 

The script was fixed in https://github.com/dmwm/CMSRucio/pull/365
However, the cleanup is still remaining. 

There are some 29 identities and 20 corresponding accounts with the issue. 
But for some reason, I am unable to correct the identities.

```python

for account in accounts:
    account_email = str(client.get_account(account)['email'])
    account_identities = client.list_identities(account)
    for identity in account_identities:
        if '@' not in str(identity['email']):  # filtering out identities with email instead of username
            identity_dn = str(identity['identity'])
            identity_type = str(identity['type'])
            print("Deleting identity: ", identity_dn, identity_type, identity['email'])
            client.del_identity(account=account, identity=identity_dn, authtype=identity_type)
            print("Adding identity: ", identity_dn, identity_type, account_email)
            client.add_identity(
                account=account, identity=identity_dn,
                authtype=identity_type,
                email=account_email)
```

The deleted identity comes back up. 
The `del_identity` only breaks the association between the identity and the account and does not actually remove it from the tables. And when `add_identity` is used to add it back, it does not update the email. 

Maybe we need a fix in rucio if we want to do this. 
However having usernames instead of emails in identities does not hurt either, so we can simply close it too.

What do you say?

**Comment by ericvaandering** [comment]
Let's close it. There is no use for emails in identities vs. accounts
