### ISSUE TITLE
Diagnose containers/datasets that seem not to have been deleted in deletion campaign

### ISSUE THREAD

**Issue by klannon** [dmwm/CMSRucio#373]

**Comment by emcgrady** [comment]
To-do:
- ~130 000 replicas still remaining
- Are there rules holding these in place?
- Are those on tape kept from a change of heart or are they failed deletions?

**Comment by emcgrady** [comment]
Most of these replicas were HC or SAM. Only 11 replicas remain and have RSE expressions for JINR_Tape.

**Comment by emcgrady** [comment]
Deletion of rules has been approved

**Comment by emcgrady** [comment]
@dynamic-entropy not yet but I'm working on that now. I will create a Jira ticket today and delete them afterwords
