### ISSUE TITLE
Add group LFNs to schema checking

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#376]
- We did not define the group/LFN correspondence here, but we can/should: https://github.com/rucio/rucio/blob/9ae42908a0e188ece017bfec1b89cf2e354b383e/lib/rucio/common/schema/cms.py#L443

**Comment by dynamic-entropy** [comment]
https://github.com/rucio/rucio/issues/6015

**Comment by dynamic-entropy** [comment]
Hello, I do not know why did this go through this chain of assignment and its removal. Sorry for that. 
We did it already here, https://github.com/rucio/rucio/issues/6015

Closing this.
