### ISSUE TITLE
PNN not filled in

### ISSUE THREAD

**Issue by stlammel** [dmwm/CMSRucio#385]
The CMS Rucio PNN attribute is not filled in for newly created RSEs. This attribute missing then makes the RSEs being skipped in the link/distance filling script (cmslinks.py). All according to Eric who checked out the new Cyprus RSE, T3_CY_UCY. The new T2_FR_GRIF RSE probably has the same issue and will need to be corrected too.
Thanks,
 - Stephan

**Comment by dynamic-entropy** [comment]
Hi Stephan
This is taken care of by DMOps during site commissioning. https://cmsdmops.docs.cern.ch/Handbook/SiteCommissioning/

@amanrique1 can you please confirm?
Also, please check if pnn is set for all rses.

**Comment by stlammel** [comment]
Ok, thanks Rahul.
Maybe it was just an oversight for UCY or added later.
- Stephan

**Comment by amanrique1** [comment]
Hi @stlammel @dynamic-entropy 
Indeed those sites don't have PNN.
The full list of 'real' sites without this attribute is
`'T2_FR_GRIF',
 'T2_US_MIT_Buffer',
 'T2_US_MIT_Tape',
 'T3_BG_UNI_SOFIA',
 'T3_CH_CERNBOX',
 'T3_CY_UCY',
 'T3_HR_IRB',
 'T3_IR_IPM',
 'T3_IT_MIB',
 'T3_MX_Cinvestav',
 'T3_TW_TIDC',
 'T3_US_NERSC',
 'T3_US_OSU',
 'T3_US_PuertoRico',
 'T3_US_Rice'`

**Comment by dynamic-entropy** [comment]
Hi @amanrique1 
Yes please, thank you.

More importantly, can you find out what `pnn` stands for?
As an additional check, can you also verify that the distance gets set (a day after) you do this? 

Unfortunately, `T3_US_FNALLPC` is not on your list. 
That would have solved the mystery of its distance not being set for this RSE. https://its.cern.ch/jira/browse/CMSTRANSF-643

fyi @ericvaandering

**Comment by stlammel** [comment]
Thanks Andres!
PNN is the old PhEDEx Node Name. I'don't know what it's used for/does in Rucio aera, though.
- Stephan

**Comment by ericvaandering** [comment]
It's a little hard to say if the PNN attribute is actually used anywhere, but it was used to determine the Rucio RSE to PhEDEx correspondence. In all cases, except for tape RSEs, it should be the same value. 

Short we should get rid of it, if we find something breaks because the PNN attribute is not set, we should fix that, not add some reference to a system decommissioned years ago. :-)

**Comment by amanrique1** [comment]
I added the attribute to the sites. Let's see if something happens related to the distance

**Comment by amanrique1** [comment]
I checked the cms links code, and this attribute is used for link matrix creation. If a site doesn't have the attribute, it will go to the except, being skipped and written on the logs.
In the specific case of `T3_US_FNALLPC` it has all the attributes except region. It considers it as None, I don't know if maybe this cause more problems later. 
It would be interesting to watch the logs where if it is crashing later. According to the code don't have region is a valid option.
@ericvaandering could you give a look at the logs to see if there is something related to this particular site? before I add the region
https://github.com/dmwm/CMSRucio/blob/db735d13a7852d4fa9a244603cff3e48e45eae36/docker/CMSRucioClient/scripts/cmslinks.py#L60

**Comment by ericvaandering** [comment]
The reason the things from FNAL are not set is that PNN is not set. But it's not set for T3_US_FNALLPC_Temp. It is set for T3_US_FNALLPC.

Considering that it's used for determining if the site is the same to set distances only, PNN may not be the right name or variable. Region looks like it would just be ignored. Of course, the region for the LPC is the same as FNAL.

**Comment by ericvaandering** [comment]
For a quick "fix" I think I will make PNN None in case it's not set. That way a link *will* get set, but maybe not a close one. Then we should open an issue to examine all of this. The answer may be to use the "site" setting from Siteconf instead.

**Comment by ericvaandering** [comment]
#546

**Comment by ericvaandering** [comment]
I assume this is fixed by #628 ? If so, please link them so things close automatically
