### ISSUE TITLE
Add Group Scope

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#388]
Add scope for group accounts, similar to - [docker/CMSRucioClient/scripts/user_to_site_mapping.py
](https://github.com/dmwm/CMSRucio/blob/c888ac4e538c8ba9459e9b6e841a1641eb962411/docker/CMSRucioClient/scripts/user_to_site_mapping.py)

We add the `group.<group_name>` scope as done for users https://github.com/dmwm/CMSRucio/blob/c888ac4e538c8ba9459e9b6e841a1641eb962411/docker/CMSRucioClient/scripts/user_to_site_mapping.py#L115

**Comment by dynamic-entropy** [comment]
Hi @ericvaandering 

Shall I change [getopt](https://docs.python.org/3/library/getopt.html) to [argparse](https://docs.python.org/3/library/argparse.html#module-argparse), in https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/scripts/user_to_site_mapping.py?

https://github.com/dmwm/CMSRucio/blob/d940d15109d58b3666773e1650ac07b5f0fc062e/docker/CMSRucioClient/scripts/user_to_site_mapping.py#L3


Also, what does `standard way` mean here, 
https://github.com/dmwm/CMSRucio/blob/d940d15109d58b3666773e1650ac07b5f0fc062e/docker/CMSRucioClient/scripts/user_to_site_mapping.py#L168

**Comment by ericvaandering** [comment]
Sure, go ahead and change it. And I don't know anymore what that comment means...
