### ISSUE TITLE
Support bulk request in list_dataset_replicas python client API

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSRucio#41]
Eric, I'm opening this issue under CMSRucio because I think it's a specific use case to CMS, which calls a Rucio dataset as a CMS block.

This issue might be more a clarification than an issue to be worked on, but it's important to bring this up. In the CMS use case, if we want to find the block replicas of a dataset, we would have to iterate and make a separate call to every single block in the dataset. Should we discuss with the Rucio team whether we can support a list of datasets to this API:
https://rucio.readthedocs.io/en/latest/api/replica.html#rucio.client.replicaclient.ReplicaClient.list_dataset_replicas

such that we can run a single call per dataset?

**Comment by ericvaandering** [comment]
Fixed in Rucio. Closing
