### ISSUE TITLE
Correct and Investigate inconsistencies in `accessed_at` field in rucio DIDs and replicas table

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#417]
The `accessed_at` fields in rucio tables are very crucial to understanding which data can be safely removed if it hadn't been accessed in N months based on DM policies, however, at the moment there are various inconsistencies that raise suspicion towards the validity of this data. 

Two crucial questions:
1. Can the erroneous values be corrected? Will this require information on how and when it happened?
2. Does the original source/reason for these inconsistencies still exist?

At the moment we observe the following numbers:
```
Invalid dates (set to INTMAX) in DIDs table: 186
Invalid dates (set to INTMAX) in Replicas table: 476
```
```
+-------------------------------------------------+--------+
|accessed_at_comparison                           |count   |
+-------------------------------------------------+--------+
|dids_accessed_at GREATER THAN max_rep_accessed_at|10894086|
|dids_accessed_at SMALLER THAN max_rep_accessed_at|265600  |
|Both Equal                                       |10099428|
|Both None                                        |65412557|
+-------------------------------------------------+--------+
```
SWAN script used to get these numbers: https://github.com/dynamic-entropy/DMSwanScripts/blob/master/accessed_at_fields_in_rucio_tables.ipynb

- [ ] Set accessed_at to the current date (or never accessed) for DIDs that have it marked as MAX_INT
- [ ] Investigate (if still present/possible) the source of these inconsistencies and propose actions to rectify them

**Comment by dynamic-entropy** [comment]
Hi @yuyiguo 
Do you have any information related to this? Are `rucio-tracers` the only external service that causes an update to the `accessed_at` field? Or are there more?

**Comment by yuyiguo** [comment]
Hi,

We don't control what the data fields are. We get the data from different resources: `/topic/cms.swpop`, `/topic/cms.jobmon.wmarchive`, and `/topic/xrootd.cms.aaa.ng` .  They define the data fields.

I saw there are consumers, like `/queue/Consumer.monitqa.cms.rucio.tracer@mb126.cern.ch` on `/topic/cms.rucio.tracer` . Did you create these `monitqa`s? Where is the code of these consumers?
