### ISSUE TITLE
Change bring-online timeout from 7 days to 30 days

### ISSUE THREAD

**Issue by KatyEllis** [dmwm/CMSRucio#422]
This longer timeout is required when we do particularly large tape stage-outs, recalling data in a queue which will take longer than 7 days. Without this, every file in the queue longer than 7 days is destined to fail (sometimes repeatedly, depending on the queue length).

For example, when we do a B-parking recall, this queue could easily be multiple weeks. With all the failures from the bring-online timeout, it is harder to see the real issues. The FTS team complained. The CERN CTA team requested the 7 day bring-online timeout to be extended to 30 days.

@ericvaandering said that there are cleverer ways to deal with this, using Rucio throttling, but we have not used this feature yet. Something to investigate for the future. For now, the bring-online timeout increase would be a good mitigation. Of course we should also think of the consequences of this change, for the longer term.

**Comment by ericvaandering** [comment]
That's great. And it's not in the DB config so it must be in flux.

**Comment by ericvaandering** [comment]
Relevant also is #419 and #322

**Comment by ericvaandering** [comment]
Actually it's just an attribute of  T0_CH_CERN_Tape. Will ping DM Ops.

**Comment by KatyEllis** [comment]
That's good. So we can change T0 for now and leave the other tape systems at 7 days and try to observe whether they ever have very long recall queues.

**Comment by dynamic-entropy** [comment]
Hi @ericvaandering, 
Are you talking about the `archive_timeout` attribute? 
This however does not match the 7-day description of the setting Katy seems to be talking about. Currently, it is set to 24 hours (86400 seconds) for T0_Tape.

**Comment by ericvaandering** [comment]
Wait, wrong value. That's the time to write data, not recall data.  Let me keep looking.

**Comment by dynamic-entropy** [comment]
`bring_online` is a conveyor config that is passed to FTS. But even that is set to 12 hrs by default. http://rucio.cern.ch/documentation/configuration_parameters/#rucio-configuration-file-ruciocfg:~:text=bring_online%3A%20Integer%2C%20bring%20online%20timeout.%20Default%3A%2043200

We set bring_online to 6.6 days here, https://github.com/dmwm/rucio-flux/blob/3de3d330dcd5ae24532c23ad07f83a18a154efb3/apps/base/cms-rucio-common.yaml#L29

**Comment by jhonatanamado** [comment]
Seems that those changes went through FTS. here a FTSJob with 30 days of bringing online:
https://fts3-cms.cern.ch:8449/fts3/ftsmon/#/job/efae8642-aed7-11ed-9e8c-fa163e1da03c

**Comment by KatyEllis** [comment]
Great, thanks @jhonatanamado ! I will try to monitor CERN tape carefully to see how it's working.

**Comment by dynamic-entropy** [comment]
Hi @KatyEllis @jhonatanamado 
I think we did not make that change yet. https://github.com/dmwm/rucio-flux/blob/e7f185814e881909775c1c348ce6dbf70d51ee9e/apps/base/cms-rucio-common.yaml#L29

Why is it set to 30 days is a mystery to me :open_mouth:

**Comment by KatyEllis** [comment]
I am also confused actually...I noticed that the FTS job sent by Jhonatan yesterday was actually started on the 18th Feb...5 days earlier...

**Comment by jhonatanamado** [comment]
okeeeeeey so this attribute can not be controlled at all by cmsRucio? I have questions if somehow we can control this attribute. Will this 30days bringing online trigger some errors or cancel the ftsrequest if is trying to bring online a corrupted file for example? That means. we will se the error automatically or we will have to wait 30 days to see those errors?

**Comment by dynamic-entropy** [comment]
It is controlled by us. As I pointed out in the code above, we set that value to the desired value and the conveyor submitter daemon passes it to FTS. How did it change to 30 days needs investigation. Are you aware of this @ericvaandering ?

@jhonatanamado I did not understand the second part of the question. Can you please clarify?

**Comment by KatyEllis** [comment]
I think that the FTS team changed the bring-online value on their side. So that could be why it's appearing as 30 days already even though the CMS change did not go through.

**Comment by dynamic-entropy** [comment]
Yeah, thanks Katy, I missed Steven's mail and wrote to him about it :sweat_smile: .
Let me change it ourselves as well.
