### ISSUE TITLE
OIDC IAM sync script not working on prod cluster

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#428]
OIDC IAM sync script is currently failling due to the oidc client has been removed by accident in a recent IAM server intervantion.

I'm going to recreate a new one and to update the secret in producion cluster.

**Comment by dciangot** [comment]
I'm moving to client credentials authN flow. So we can get rid of the oidc-agent installation on the sync script dockerfile.

We can test it in the new integration test

**Comment by dciangot** [comment]
#475 tested on integration test.
Once in harbor it has to be activated into prod sync script

**Comment by dynamic-entropy** [comment]
Hi @dciangot 

Are we ready to move this forward?

**Comment by dciangot** [comment]
@dynamic-entropy yes, I think #475 is ready to be deployed

**Comment by ericvaandering** [comment]
@dciangot is this still an issue? This is our remaining issue from Q3 which was never moved forward

**Comment by dciangot** [comment]
closing. continuing on new error evidence on dedicated issues
