### ISSUE TITLE
rule Approval UI disappeared

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/CMSRucio#436]
Probably is an issue since the last upgrade. Site admin from FR_Tape can not approve the rules using the UI. https://ggus.eu/index.php?mode=ticket_info&ticket_id=160762

**Comment by dciangot** [comment]
Everything looks back to normal after the usual reboot strategy :/

Closing this, will reopen if the behavior will reappear in the next days

**Comment by dciangot** [comment]
re-opening, since the problem still there. the rule page does not show any approve button.

**Comment by dciangot** [comment]
@ericvaandering do you think that can be related to the version mismatch with the server?

**Comment by dynamic-entropy** [comment]
Hi @dciangot 
Is this still relavant?

**Comment by KatyEllis** [comment]
This is a good question. I haven't heard complaints about not being able to approve via the web UI, but maybe admins started doing it via the CLI. I do it using the CLI myself, but if I click on a UI link asking for approval today, I do not see a way to approve using the UI...so maybe it is actually not fixed.

**Comment by dciangot** [comment]
Still, we are getting closer to the new webUI release. I'm not sure we have effort to put into this, neither a strong need. I'd close this, and re-open only if major complains will come.

**Comment by dciangot** [comment]
re-opening this since Dima reported the problem as persistent. Eventhough the webUI will be reworked, this misbehavior is reported as critical from the operations stand point. @drkovalskyi feel free to comment/correct if I got it wrong.

@ericvaandering how should we proceed for this? Do we have any chance to sort out the problem before the new UI is out (not sure it will come out in sept as promise some time ago)

**Comment by drkovalskyi** [comment]
The new UI was expected to be available in May. I would suggest that we try to integrate it as soon as possible and start testing. It makes more sense to invest time in a new thing, but in general WEB UI is a major limitation. People don't find CLI interface user friendly.

**Comment by ericvaandering** [comment]
We have an opportunity now, with the new production cluster coming, to request an additional DNS alias for our cluster where we can run both UIs side by side. To my knowledge, no one from CMS has looked at the new UI at all, so this would be a good chance. I know Connor is interested in this as well.

**Comment by ericvaandering** [comment]
@cmoore24-24

**Comment by dynamic-entropy** [comment]
Closing this, the rule approval works with the old UI. 
We are already waiting for the new UI in other tickets: https://github.com/dmwm/CMSRucio/issues/404

Coincidentally the ticket number is **404** :)
