### ISSUE TITLE
Rucio howTo guide update and cleanup

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#440]
Includes 

- [x] #668

**Comment by cmoore24-24** [comment]
Here is the Google Drive where I am keeping the materials I have written up for Rucio: https://drive.google.com/drive/folders/1HFxCuoaEfgOvxNC_8ZolU2kdgVxr1jEK?usp=sharing

**Comment by dynamic-entropy** [comment]
Hello, I am unassigning myself, since I am not actively working on this. 
I am not sure if this issue is even needed. 
Let me know if any help is required.

**Comment by cmoore24-24** [comment]
I'm pretty happy with the docs I've written up. All of my materials can be found [here](https://drive.google.com/drive/folders/1HFxCuoaEfgOvxNC_8ZolU2kdgVxr1jEK?usp=sharing), including a general set of docs, a glossary, and links to existing resources. Finding these a more permanent home should be the next step.

**Comment by dynamic-entropy** [comment]
Hi @cmoore24-24 
Thank you for taking care of this. 
I think DMDocs would be the appropriate permanent place to house these, https://cmsdmops.docs.cern.ch. 
https://gitlab.cern.ch/cmsdmops/Documentation/-/tree/master/docs

(And if there is something general to rucio, we can create a PR here, https://github.com/rucio/documentation ). 

Please go ahead with the move or let us know if you have questions. It would be nice to bring this up in today's meeting too.

**Comment by ericvaandering** [comment]
I disagree. This documentation is primarily aimed at users. https://twiki.cern.ch/twiki/bin/view/CMS/Rucio has a section for such documentation, some of it duplicated with what is in Connor's slides. 

There is also at least this section of the workbook: https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookFileTransfer which is CMS's main source of user documentation. 

I think I would like to see Connor's work fed back into the first link as User documentation, the workbook updated to cover some basics, get rid of the PhEDEx stuff, and link to the user documentation. 

To the extent Ops needs to reference user-facing documentation, it should reference it, not duplicate it. Of course there are CLI and python API functions of more use to ops than users and those should not be exposed to users so they are not confused.

**Comment by cmoore24-24** [comment]
I've created A twiki page that hosts writeups of all the user-focused documentation I've created, found [here](https://twiki.cern.ch/twiki/bin/view/CMS/RucioBeginnersGuide). This has been built as a subtopic to the main Rucio page, [here](https://twiki.cern.ch/twiki/bin/view/CMS/Rucio). I still need to clean up the WorkBook page, but I will be able to link to the new guide once I have.

**Comment by ericvaandering** [comment]
I'd like to understand how this "Beginner's guide" relates to the user section on the main Rucio page. Can we integrate these better?

**Comment by ericvaandering** [comment]
@cmoore24-24 Anything new here? Can we close this or is it still waiting on something?

**Comment by cmoore24-24** [comment]
Hi @ericvaandering, I think mostly complete. Katy had a few suggestions that I've since implemented, so we're just waiting on her having a free moment to do one last look over. But I think for all intents and purposes, what is currently published on the workbook is the final draft.

**Comment by cmoore24-24** [comment]
Having recevied and implemented feedback from Katy, I think this can be closed.
