### ISSUE TITLE
Clean rucio "subscription_history" table.

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#442]
Can you please empty the rucio subscription_history table?

A month ago, `subscription_history` was an empty table.
We wanted to use it to store updates to the subscription and so I enabled the setting (subscription.keep_history=True). 
However, there was a bug in the code related to this setting. https://github.com/rucio/rucio/issues/6109

This meant instead of just recording updates to the subscription itself, it started storing rows every time a did was processed.
I have disabled it and hopefully solved the bug.

We want to clean it up so that when we enable it again, we have consistent data.
The table is not used by any other service or even rucio itself, it is just to store updates made by us.

FYI @ericvaandering

**Comment by yuyiguo** [comment]
do you want to remove everything in subscription_history?  Beside of you, anyone or apps  do use this table?

**Comment by ericvaandering** [comment]
remind me, do we have the patch for 6109 in our Rucio? If not, this is going to continue to accumulate until we upgrade to 1.31 so we will have to do it again.

**Comment by dynamic-entropy** [comment]
Hi Eric, we do not have the patch in our rucio. But we do not intend to switch it on again until we need it. 
So, I believe, for now, cleaning up is good enough. 
We do that patch if needed. One more history missed it fine I guess.

**Comment by ericvaandering** [comment]
Oh, right. Keeping the history is an option. OK, good enough.

**Comment by dynamic-entropy** [comment]
Hi Yuyi
Yes, we can get rid of everything. Its function is to store changes to the subscription metadata.
But we were not storing it till now. So, I can say with good confidence, that no one was relying on the previously empty table.

**Comment by yuyiguo** [comment]
Thanks for confirming this. I will do it tomorrow when @ericvaandering passes me the new password.

**Comment by yuyiguo** [comment]
It is done.
