### ISSUE TITLE
Rucio is taking a lot of time (more than a month) to mark a file replica as available.

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/CMSRucio#447]
This issue comes from the following JIRA https://its.cern.ch/jira/browse/CMSDM-12 where Tier0 reported some stuck rules with file exist error. After debugging what was happening at the beginning seems that the Tape site was having some issues archiving the files from the buffer to the tape. 

But then once the file was properly archived, rucio is not available to mark that file as available.

```
gfal-xattr root://eoscms.cern.ch:1094//eos/cms/tier0/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root user.status
ONLINE
[jamadova@lxplus766 ~]$ gfal-stat root://eoscms.cern.ch:1094//eos/cms/tier0/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root
  File: 'root://eoscms.cern.ch:1094//eos/cms/tier0/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root'
  Size: 3091885063	regular file
Access: (0400/-r--------)	Uid: 134507	Gid: 1399	
Access: 2023-02-24 13:03:18.000000
Modify: 2023-02-24 13:03:18.000000
Change: 2023-02-24 13:03:18.000000
[jamadova@lxplus766 ~]$ rucio list-file-replicas --all-states cms:/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root
+---------+---------------------------------------------------------------------------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SCOPE   | NAME                                                                                                    | FILESIZE   | ADLER32   | (STATE) RSE: REPLICA                                                                                                                                                                             |
|---------+---------------------------------------------------------------------------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (A) T0_CH_CERN_Disk: davs://eoscms.cern.ch:443/eos/cms/tier0/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root                              |
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (A) T1_DE_KIT_Tape: srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root |
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (A) T2_CH_CERN: davs://eoscms.cern.ch:443/eos/cms/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root                                         |
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (U) T0_CH_CERN_Tape: root://eosctacms.cern.ch:1094//eos/ctacms/archive/cms//store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root               |
+---------+---------------------------------------------------------------------------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+ 
```

And as usual Rucio is still trying to copy that file triggering new [fts jobs](https://fts3-cms.cern.ch:8449/fts3/ftsmon/#/job/df0d89e0-cd6e-11ed-8d07-fa163ebc953f) but those are failing with file exist error.

This behavior should be improved. The file is now at archived at Tape? and is not in the buffer?. So is this particular case (file not in buffer )included in https://github.com/rucio/rucio/issues/4447 ?

**Comment by dciangot** [comment]
@ericvaandering ?

**Comment by jhonatanamado** [comment]
This is now a high priority. Files with this behavior can only be properly archived at tape if:

- File is deleted from buffer.
- Rucio will try one more time with the transfer, this time transfers will not fail with File exist bc file was deleted from buffer
- File will sit in the buffer. 
- Finally will be archived by Tape [OpenData_Link](https://monit-opensearch.cern.ch/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-4M,to:now))&_a=(columns:!(data.event_type),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'1972b850-d0b8-11ea-a34a-f59641c8979f',key:data.name,negate:!f,params:(query:%2Fstore%2Fdata%2FCommissioning2023%2FNoBPTX%2FRAW%2Fv1%2F000%2F363%2F833%2F00000%2F113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root),type:phrase),query:(match_phrase:(data.name:%2Fstore%2Fdata%2FCommissioning2023%2FNoBPTX%2FRAW%2Fv1%2F000%2F363%2F833%2F00000%2F113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'1972b850-d0b8-11ea-a34a-f59641c8979f',key:data.dst_rse,negate:!f,params:(query:T0_CH_CERN_Tape),type:phrase),query:(match_phrase:(data.dst_rse:T0_CH_CERN_Tape)))),index:'1972b850-d0b8-11ea-a34a-f59641c8979f',interval:auto,query:(language:kuery,query:''),sort:!()))

While this behavior should be expected to be done by Rucio , so far needs a "manual" intervention by an operator.  Only after the file was deleted from  CTA buffer. Rucio was able to trigger a "succesfull" fts job and the file is now archived at CTA.

```
rucio list-file-replicas --all-states cms:/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root
+---------+---------------------------------------------------------------------------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SCOPE   | NAME                                                                                                    | FILESIZE   | ADLER32   | (STATE) RSE: REPLICA                                                                                                                                                                             |
|---------+---------------------------------------------------------------------------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (A) T0_CH_CERN_Disk: davs://eoscms.cern.ch:443/eos/cms/tier0/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root                              |
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (A) T1_DE_KIT_Tape: srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root |
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (A) T2_CH_CERN: davs://eoscms.cern.ch:443/eos/cms/store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root                                         |
| cms     | /store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root | 3.092 GB   | 737d6e11  | (A) T0_CH_CERN_Tape: root://eosctacms.cern.ch:1094//eos/ctacms/archive/cms//store/data/Commissioning2023/NoBPTX/RAW/v1/000/363/833/00000/113ef6bb-0604-4a8a-9b6d-a8bd7cec176a.root               |
+---------+---------------------------------------------------------------------------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

I would like to keep this issue open until a new development takes into account this corner cases .

**Comment by germanfgv** [comment]
@jhonatanamado Is there any new information on this. This is becomming a serios issue for T0.

**Comment by jhonatanamado** [comment]
hi @germanfgv , I applied the work-around during the weekend. Could you check again if the situation at least improve?

**Comment by germanfgv** [comment]
@jhonatanamado the situation looks better now indeed. Thanks for the fix.

**Comment by amanrique1** [comment]
@dciangot @ericvaandering @dynamic-entropy 
We are having more cases similar to this one. This week T0 reported new cases on the following JIRA ticket: https://its.cern.ch/jira/browse/CMSTRANSF-704

In this new case, we have 2 files with size 0 and user.status=UNKNOWN

`
rucio list-file-replicas --all-states cms:/store/data/Run2023C/ParkingDoubleMuonLowMass4/RAW/v1/000/367/758/00000/1eaad005-3e77-4ffd-aa1c-818443b750a1.root
+---------+-------------------------------------------------------------------------------------------------------------------+------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SCOPE   | NAME                                                                                                              | FILESIZE   | ADLER32   | (STATE) RSE: REPLICA                                                                                                                                                                         |
|---------+-------------------------------------------------------------------------------------------------------------------+------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| cms     | /store/data/Run2023C/ParkingDoubleMuonLowMass4/RAW/v1/000/367/758/00000/1eaad005-3e77-4ffd-aa1c-818443b750a1.root | 4.074 GB   | fb1bd2f9  | (A) T0_CH_CERN_Disk: davs://eoscms.cern.ch:443/eos/cms/tier0/store/data/Run2023C/ParkingDoubleMuonLowMass4/RAW/v1/000/367/758/00000/1eaad005-3e77-4ffd-aa1c-818443b750a1.root                |
| cms     | /store/data/Run2023C/ParkingDoubleMuonLowMass4/RAW/v1/000/367/758/00000/1eaad005-3e77-4ffd-aa1c-818443b750a1.root | 4.074 GB   | fb1bd2f9  | (U) T0_CH_CERN_Tape: root://eosctacms.cern.ch:1094//eos/ctacms/archive/cms//store/data/Run2023C/ParkingDoubleMuonLowMass4/RAW/v1/000/367/758/00000/1eaad005-3e77-4ffd-aa1c-818443b750a1.root |
+---------+-------------------------------------------------------------------------------------------------------------------+------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


gfal-xattr root://eosctacms.cern.ch:1094//eos/ctacms/archive/cms//store/data/Run2023C/ParkingDoubleMuonLowMass4/RAW/v1/000/367/758/00000/1eaad005-3e77-4ffd-aa1c-818443b750a1.root user.status
UNKNOWN
`

`
rucio list-file-replicas --all-states  cms:/store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root
+---------+----------------------------------------------------------------------------------------------------------------------------------+------------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SCOPE   | NAME                                                                                                                             | FILESIZE   | ADLER32   | (STATE) RSE: REPLICA                                                                                                                                                                                        |
|---------+----------------------------------------------------------------------------------------------------------------------------------+------------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| cms     | /store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root | 1.437 GB   | 3471b20b  | (A) T1_US_FNAL_Disk: davs://cmsdcadisk.fnal.gov:2880/dcache/uscmsdisk/store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root       |
| cms     | /store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root | 1.437 GB   | 3471b20b  | (A) T0_CH_CERN_Disk: davs://eoscms.cern.ch:443/eos/cms/tier0/store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root                |
| cms     | /store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root | 1.437 GB   | 3471b20b  | (A) T1_IT_CNAF_Disk: davs://xfer-cms.cr.cnaf.infn.it:8443/cmsdisk/store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root           |
| cms     | /store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root | 1.437 GB   | 3471b20b  | (U) T0_CH_CERN_Tape: root://eosctacms.cern.ch:1094//eos/ctacms/archive/cms//store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root |
+---------+----------------------------------------------------------------------------------------------------------------------------------+------------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


gfal-xattr root://eosctacms.cern.ch:1094//eos/ctacms/archive/cms//store/data/Run2023C/ParkingDoubleMuonLowMass2/MINIAOD/PromptReco-v3/000/367/742/00000/9a63b2f8-19aa-4ae1-ad24-6fbc28d9cffc.root user.status
UNKNOWN

`

**Comment by dynamic-entropy** [comment]
Hi @amanrique1 
I believe we are mixing two problems in this ticket. 
1. According to the issue title: The original intention of the ticket was to report, a delay in updates to the rucio internal state (under the jurisdiction of the conveyor-finisher) after a transfer has been marked successful in rucio. 
However, in the description, I also find
2. Unsucessful transfer to tape with residual replicas, leading to FILE EXISTS errors. 
The case you describe is 2. 
@ericvaandering @dciangot What do you suggest as a temporary solution for operations to unstuck such transfer?
For a final solution, we are still waiting for the FTS to implement the `--overwrite-disk` flag. 
We aim to do the same with `overwrite-corrupted-files` as this is preferred by T0 (@beer4duke ). https://github.com/dmwm/CMSRucio/issues/596

**Comment by dynamic-entropy** [comment]
I am closing this. 
The first issue, will be handled in #633 
and the second one in #640
