### ISSUE TITLE
Add basic schema checka and linting in storage.json

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#450]
Even though our script correctly handles invalid json by ignoring updates. It requires manual debugging to find out why the updates did not take place. 

I propose we put a CI on each repo in siteconf for the storage.json file. 
This way the editors are informed about these basic errors before they commit.

- [ ] Add Basic Linting
- [ ] Add Schema checks?

**Comment by stlammel** [comment]
There is a SAM tests waiting for the token submitted tests/a fixed HTCondor version that will checl syntax and mandatory keywords, so i don't think we want to load this onto CI of the ever-changing GitLab.
The script should just skip storage.json files it can't handle.
- Stephan
