### ISSUE TITLE
Allow special permisssion to set rse usage

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#468]
T0_CH_CERN and T2_CH_CERN_Disk need to update and change the rucio usage limits in sync with the EOS quotas. 

[Data Management Jira Comment ](https://its.cern.ch/jira/browse/CMSTRANSF-542?focusedCommentId=4799170&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4799170)

**Comment by dynamic-entropy** [comment]
Hi @ericvaandering 

I suggest adding a `<site_name>.<admin>` (or `quota_manager` or anything else) attribute to the accounts. And use that to give permissions. 
Or would you prefer to add a list of accounts in the rse attributes instead? Like the `quota_approvers` and `rule_approvers`?

Please let me know and I will proceed accordingly.

**Comment by ericvaandering** [comment]
For now I would just actually use the quota_approvers list. We don't actually have different things on the source end for these lists anyhow, so why keep making up identical RSE attributes?

**Comment by dynamic-entropy** [comment]
I did not see relevant people on the list. And I am not sure if they belong to the quota approvers list.

Additionally, I see a lot of people added to that list (quota_approvers)
Okay, let me ask Ops for a review of the list and if this can be used. I do not want to create a new one too.

**Comment by ericvaandering** [comment]
OK. If they really are different lists of people in CRIC, then we should add another list to Rucio

**Comment by dynamic-entropy** [comment]
Hi @ericvaandering 
This will be the group that we need to sync it to. https://cms-cric.cern.ch/api/accounts/group/query/?json&name=CMS_TIER_0_OPS. Thanks, https://github.com/Panos512.

These are T0 operators. And need permission to change `rse_usage` at `T2_CH_CERN` and `T0_CH_CERN_Disk` only. 
So I will create a list named `site_capacity_managers` for both of these sites that will be synced from that list. 
Is it fine?

Also, another confirmation, all `rucio account` names are the same as Cern usernames right (`login` in the above CRIC link)?

**Comment by ericvaandering** [comment]
Ah, I thought this was needed per site. It’s one group of people for the whole experiment?

Then, maybe consider a group account with each of their DNs as an identity added to it. Then give them the right to set the usage on any RSE.

Yes, the account names come from CRIC which gives the CERN account name.

**Comment by ericvaandering** [comment]
OK
