### ISSUE TITLE
Cleanup of country-XX attribute from permissions and account attributes

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#469]
@ericvaandering Do we still need these?
The lines checking for this attribute are commented. Additionally, it adds attributes as `country-XX`, i.e `XX` instead of actual country codes, which makes it of no use anyways. 

https://github.com/dmwm/CMSRucio/blob/9ca5979180a7734ba1e13d786569e5a5c1c2bbf1/docker/CMSRucioClient/scripts/syncUserRoles.py#L92-L97

Additionally, we need to remember to clean up these attributes from all affected accounts as well.

**Comment by ericvaandering** [comment]
We’ve never used country admins (That’s kind of an ATLAS thing).

**Comment by dynamic-entropy** [comment]
The code setting this was removed in https://github.com/dmwm/CMSRucio/commit/f108ab272985af93376fffe3ca1ee7ed6cae1080. 

We can remove the extra attributes using the CLI now.

**Comment by dynamic-entropy** [comment]
DONE
