### ISSUE TITLE
Fix setQuotas script

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#470]
https://github.com/dmwm/CMSRucio/blob/ddbad58abb48225f175137d34609a26d7cb151ea/docker/CMSRucioClient/scripts/setSiteQuotas#L33

`record['_source']['data']` is of type `dict` and thus cannot be an element of a set.

---- 

Write a custom function to get the list of distinct site info. 

----

Logs from the corn Job Pod:
```
+ ./setSiteQuotas
Setting quotas
Traceback (most recent call last):
  File "./setSiteQuotas", line 33, in <module>
    sites = sorted(list(set([record['_source']['data'] for record in j['responses'][0]['hits']['hits']])))
TypeError: unhashable type: 'dict'
```

**Comment by ericvaandering** [comment]
OK, that's a new problem. The data format must have changed.

**Comment by dynamic-entropy** [comment]
Hi @ericvaandering 
Do we even need this script? 

This only sets the quota for the "transfer_ops" account. 
Which being an `admin` account does not have any effect.

**Comment by ericvaandering** [comment]
I would prefer to keep this running. IIRC, Nick wanted eventually to remove admin from transfer_ops and maybe that remains a good goal.

**Comment by ericvaandering** [comment]
All your points are valid, and we've discussed subscriptions only for production, but it wasn't practical. I don't remember the reasoning. They are, somehow, using the size of sites to make weighting decisions.

In general we have quotas to make it harder for one person making a mistake from screwing everything up. Maybe, in this case, it doesn't help us at all.

We can get rid of this script, keep it, it makes no difference operationally right now, I agree. But I also don't feel its a large problem that we have.

**Comment by dynamic-entropy** [comment]
Its code, idea and procedure are already captured in `setSiteCapacity` now. 
So, I will just clean it up and instead add logic for setting quotas for `local_accounts` here.
