### ISSUE TITLE
Loadtests do not recover if the test file is 'Lost' 

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#515]
E.g. issue: https://its.cern.ch/jira/browse/CMSDM-59

We should probably filter out `Lost` files after this
https://github.com/dmwm/CMSRucio/blob/682126387970d01f47a2b5fdfaeeb96705ea159d/docker/CMSRucioClient/loadtest/loadtest.py#L304

And further detach them from the dataset.

**Comment by dynamic-entropy** [comment]
Hi @stlammel

What is the policy for files at `/store/test/` at sites?
We have another incident due to this issue, https://its.cern.ch/jira/browse/CMSDM-77 

I will take the case into account in the script, but wanted to know out of curiosity, if we know why files go missing at times

**Comment by dynamic-entropy** [comment]
One more thing I see is, no rule protects that file at the source. 
Maybe a solution for this should be put in place too.

Most of the time these shall be protected by, 
1. virtue of being active sources
2. very recently used

**Comment by stlammel** [comment]
Hallo Rahul,
   i assume you mean retention/deletion policy, right? There is no deletion
policy or suggestion for the area. Some files, like the /store/test/xrootd/<sitename>
link stay forever. If a site admin sees large, old files i would expect her/him
to delete them without notice. The /store/test/rucio area is generally known
and i would not expect sites to manually delete/manage files in there,
except trying to "correct" things. 
   Thanks,
       cheers,  Stephan
