### ISSUE TITLE
Problem creating Rucio user container

### ISSUE THREAD

**Issue by andelpe** [dmwm/CMSRucio#531]
Hi,

I was trying to follow instructions at https://twiki.cern.ch/twiki/bin/view/CMSPublic/RucioUserDocsContainers and create a container for several datasets. I was trying to do it for the general site account for local space, i.e.: t2_es_ciemat_local_users, but I can't.

Context: our goal is to subscribe to several Rucio datasets of interest to the T2_ES_CIEMAT local analysis community. The list will evolve with time, that's why I intended to create a container where I can add new interesting datasets in the future. And that's also why I wanted to use t2_es_ciemat_local_users account, instead of a particular account of a single person.

My first doubt is if I should try to create a container in 'user' or 'group' scope. If I choose 'group', should I then set '/GROUP' (instead of '/USER') as datatier? This is not indicated in the twiki.

In any case, if I just follow the examples and do the following, it fails:
```
  $> rucio add-container user.t2_es_ciemat_local_users:/data/NanoAOD_2023/USER

2023-05-29 11:24:40,693    ERROR    Provided object does not match schema.
Details: Problem validating did : 'user.t2_es_ciemat_local_users' does not match '^(cms)|(logs)|(user\\.[a-z0-9-_]{1,20})$|(group\\.[a-z0-9-_]{1,19})$'

Failed validating 'pattern' in schema['properties']['scope']:
    {'description': 'Scope name',
     'pattern': '^(cms)|(logs)|(user\\.[a-z0-9-_]{1,20})$|(group\\.[a-z0-9-_]{1,19})$',
     'type': 'string'}

On instance['scope']:
    'user.t2_es_ciemat_local_users'
```

The error message suggests that the problem is that the account name is too long (it seems that the limit is 20 chars for user, 19 for group):

If I just use a shorter name for the scope, this pattern validation succeeds, but it fails due to authorization error, e.g.:
```
$> rucio add-container user.t2_es_ciemat_local:/data/NanoAOD_2023/USER
2023-05-29 11:24:30,659    ERROR    Access to the requested resource denied.
Details: Account t2_es_ciemat_local_users can not add data identifier to scope group.t2_es_ciemat_local
```

So... what can we do? Can the chars limit be raised? I guess most user groups names are longer than 19 chars.

Should we instead follow a different approach?

Thanks!

**Comment by dynamic-entropy** [comment]
Hi @andelpe 

You can create rules on whatever datasets you need as the list evolves. 
What is the intention of containerising them? 

In the end, the effort remains similar on your end:
1. A rucio command to create a rule
2. A rucio command to attach the dataset to the container

In fact, in the former case, you have the flexibility of managing them separately, for e.g with different lifetimes, so you don't forget to get rid of data, not in use.

**Comment by andelpe** [comment]
Well. The one container and one rule solution seems more elegant (precisely, as https://twiki.cern.ch/twiki/bin/view/CMSPublic/RucioUserDocsContainers describes). Let me notice that we are talking about hundreds of datasets (those matching certain patterns).

In practical terms, I am not sure if it really buys us much effort-wise, but it looks attractive especially in order to keep track of what data we are requesting. I mean, I think I could use `rucio list-content <container>` to know exactly what is included in the rule for this activity. If I create 400 rules, then I need to list those rules to be sure of what we are replicating already... may I use DID patterns with `rucio list-rules`?

By the way, I understand that it's not possible to use DID patterns with `rucio add-rule`, right? That would be quite interesting for us, if we go the way of 1 rule per dataset.

One last question, how bad a client would I be if I periodically try to add all datasets matching our patterns using `rucio add-rule --skip-duplicates` (with the goal of creating rules only for the new matching datasets)?

Cheers,
   Antonio

**Comment by ericvaandering** [comment]
Options for you:

Use a scope on a user account for the container. We don't have scopes for the local accounts since they are intended only to be used for quotas for a group of people and weren't proposed for creating new data (or containers)

Use a subscription. This is a "rule generator" and would accomplish, automatically on creation, your desire to match a pattern of dates and apply a rule. You may need an operator to set this up, not sure of the permissions.

We also could add a scope for you if using a user scope really doesn't work.

I don't think we can adjust the length easily as this probably involves changing the underlying database.

**Comment by andelpe** [comment]
For the first option, you mean use a scope on a individual user account, like my personal one, e.g.? I would rather not do that if it's avoidable (I may leave, or just want to delegate the job to somebody else).

On the other hand, subscriptions may be just what we want. I didn't know about them (I've noticed that one creates them with `rucio-admin` CLI, rather than just `rucio`). That particular command doesn't seem to be as well documented as others (e.g., so far I was unable to find an example). How can I find out if I would need operator help? Should I just try it?

Thanks for all the comments!

**Comment by andelpe** [comment]
Hi, again. I went ahead and tried to create a subscription, but I got a permission error: "requested resource denied". Neither my personal account are allowed to add subscriptions (it says: "Account t2_es_ciemat_local_users can not add subscription").

I've got a few questions:

- Can this permission problem be solved somehow? If the solution is to ask an operator for the creation of any particular subscription, then I am not sure if this is the most practical solution either (it might be for a single case, but perhaps not for the long term).
- The subscription examples I found also specify a scope. "cms" should be used as scope in this case, right? I understand that this is the scope of the data I am trying to create replications rules for (not creating a new element, like in the containers case). 
- In the examples, I see the data to match is specified with things like "project", "dataType", or "tag". However, the docs talk about using dataset names or patterns. How would that be specified? Something like "pattern": "..."?

If the subscription option is not the best one in the end. Then we are left with:

- Creating a new scope as you suggested. How would this work? Something like "user:ciemat_users", and t2_es_ciemat_local_users is allowed to create a container there? 
- Creating one rule per dataset as originally suggested. This would work, but I guell we'll need to keep track of our subscriptions ourselves, so that we can easily now what we're replicating, and review periodically to see if we need to add more data, etc.

Cheers,
   Antonio

**Comment by dynamic-entropy** [comment]
Hi Antonio

Yes, at the moment, only admins are allowed to create subscriptions. Whether or not this should be extended to other users and under which constraints require some discussion and thus cannot be promised soon.
If you still want answers to your questions on creating subscriptions, let me know. 
Also, does the data that you want replicated, follow a pattern? - That is how we use subscriptions when we know upfront where new data needs to be replicated. 
Please note that subscriptions do not work on old (already registered) data.

The scope creation part can be done. 
However, as I argued above, it does not change anything about your concerns: "But I guess we'll need to keep track of our subscriptions ourselves, so that we can easily now what we're replicating, and review periodically to see if we need to add more data, etc."

With a container, you would do:  `rucio list-contents <group.t2_es_ciemat>` to get the data info
With individual rules you would do: `rucio list-rules --account <group.t2_es_ciemat_local_users>` to get the same info

**Comment by andelpe** [comment]
Hi Rahul,

Given your answer, no, I don't think subscriptions will do. Our data of interest does follow (several) patterns (e.g. `/SingleMuon/*/NANOAOD`), but we are also interested in replicating existing data).

Regarding the one container and the individual rules, I still think there is a difference. With the container, I understand that I could list the contents of a specific container (there might be more). While the list-rules example you show would return all data belonging to 't2_es_ciemat_local_users', and there may be more than what we are discussing here. I mean, with containers we might discriminate, let's say, two or three grand groups of interesting data, even if they all belong to the same account. 

Sorry if I'm too picky here. I was just trying to find the best way to deal with this model long term (maybe useful for others also). If creating an additional scope represent significant effort, or it would be too "non-standard", then I'm OK with the individual rules approach. I've already come to terms with it :-)

Thanks again.

**Comment by dynamic-entropy** [comment]
Hi Antonio 

Thank you for the details. 
So, you have two questions pending for me: 
1. User subscriptions (we will discuss this but won't come into effect soon)
2. Scope of `*local_users` account (I have been personally inclined to add these, so if we go ahead with these, we will create them for you by EOD)

We didn't get a chance / to expose too much of rucio to users yet. So even the basic things are not standard and we highly appreciate your input and patience. 

Thanks

**Comment by dynamic-entropy** [comment]
Hi @andelpe 

I have added the scope `group.t2_es_ciemat` to  t2_es_ciemat_local_users. 
You can now create containers using it.

So from your first comment, the command would be 
`rucio add-container group.t2_es_ciemat:/data/NanoAOD_2023/USER`

And then you can use
`rucio attach group.t2_es_ciemat:/data/NanoAOD_2023/USER <Other DIDs>` to add them to your container. 

Please let me know if you need anything else.
Thanks

**Comment by andelpe** [comment]
Things seem to work as expected!
Many thanks!

**Comment by andelpe** [comment]
Um... sorry, not *everything* seems to work as expected.

Yesterday I created the container, attached one dataset to it, then added a replication rule to our site, later I attached a new dataset to the container. Both attached datasets contain just one file.

Today, I see that only the file of the first dataset has been replicated to our site. However, Rucio is reporting that the state of the rule is OK (not replicating or stuck). That is, it does not seem that any transfer is pending, and I haven't seen any transfer attempt for that second dataset file.

According to the twiki**, newly attached datasets should be picked up by the already existing replication rule. And, indeed, that's what motivated choosing this solution :(

Is there something I'm not understanding? Should I do something to trigger the replication of new attached datasets?

** https://twiki.cern.ch/twiki/bin/view/CMSPublic/RucioUserDocsContainers: "The beauty of this approach is that when the user decides to add/remove datasets to their container, no new replication rules are needed - Rucio handles all the data-transferring automatically as part of the already existing rule."

**Comment by andelpe** [comment]
Hi, Rahul. 

With the switch, things seem to work fine. I had removed the replication rule (as an additional test), so I added it again, I then attached a new file and it has been quickly replicated, just as I'd expect.

Should I now proceed to attach all our ~400 datasets, or do you want me to test something else?

Thanks

Antonio

**Comment by dynamic-entropy** [comment]
Hi Antonio

You may go ahead with attaching your datasets. 
Thank you for all the help.

You may open a discussion in the same repo if you have more questions or missing documentation or any other suggestions.
