### ISSUE TITLE
Collection attachement to containers do not trigger rule re-evaluation

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#537]
The `add_collections_to_container` function does not populate the UpdatedDIDs table on the `ATTACH` operation. With the new upgrade the `use_temp_tables` is set to `True` by default. 
 
 https://github.com/rucio/rucio/blame/17cb67e4cb97448d65feca82b77ee71b75cca337/lib/rucio/core/did.py#L658
 
 For a quick fix, I have set `core.use_temp_tables` to `False`. 
 
 Todos:
- [x] Set it to True / Remove the config(Default is True)  https://github.com/dmwm/CMSRucio/issues/556

**Comment by dynamic-entropy** [comment]
https://github.com/rucio/rucio/issues/6234

**Comment by ericvaandering** [comment]
Please add this to the project. I didn't realize you made this change until just now and we need to put it back when there is a fix.

**Comment by dynamic-entropy** [comment]
Done. 
Temporary tables will be made mandatory here, https://github.com/rucio/rucio/issues/6238, so that config will become obsolete.

**Comment by ericvaandering** [comment]
The scripting part is a little different. (Or this is a meta issue). I'm going to reopen it.

**Comment by dynamic-entropy** [comment]
I have removed the config for `use_temp_tables` and did a manual test for rule-revaluation on attach too. 
```
➜  ~ rucio-admin config delete --section core --option use_temp_tables
Deleted section 'core' option 'use_temp_tables'
```
