### ISSUE TITLE
Rucio Web site does not show the full list of my rules

### ISSUE THREAD

**Issue by andreypz** [dmwm/CMSRucio#568]
Hello,
I am using rucio web interface to create transfer rules for my analysis: https://cms-rucio-webui.cern.ch/r2d2
It works great generally. However, recently I noticed that I can no longer see all the rules I created. I can see only the last  rules, but I have a lot more older rules. I make sure to change the display interval (500 days), but it has no effect. 
It worked before. Please take a look.

And another issue: you have a link to a survey at the top of the page, but it does not work. Maybe you should remove or update it.

Best,
Andrey

**Comment by dciangot** [comment]
This is related to https://github.com/dmwm/CMSRucio/issues/436

We need to plan for moving away from the current webUI asap

**Comment by dynamic-entropy** [comment]
Hello @andreypz 
It seems to have been resolved. Can you please confirm if it works as expected for you too?

**Comment by andreypz** [comment]
Hello,
Looks like it does show my older rules now.
However it only shows the rules created via the web interface. 
Recently I've been creating rules with rucio command line and those are not shown on the web page.

**Comment by dynamic-entropy** [comment]
Hmm, Can you inspect if there aren't any filters; that might be causing this? There is essentially no difference between the two.

**Comment by andreypz** [comment]
Indeed, the 'Activity' filter was set to `User Subscriptions`. 
Removing this filter now gives me all my rules, including those created with a command line.
Perhaps the `Activity` field should be empty by default?

Anyway, thanks for making it work!
