### ISSUE TITLE
Cannot add new replicas from T2_UK_SGrid_Bristol_Temp and T2_DE_DESY_Temp

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CMSRucio#577]
In CRAB Rucio ASO, we rely on `lfns2pfns()` with normal RSE name to get PFN of temp\_RSE.
However, all T1/T2 sites work (so far) except these 2 temp\_RSEs:
- `T2_UK_SGrid_Bristol_Temp`: Got `RSEProtocolNotSupported` exception:

    ```
    RSEProtocolNotSupported: RSE does not support requested protocol.
    Details: No protocol for provided settings found : {'availability_delete': True, 'availability_read': True, 'availability_write': True, 'credentials': None, 'deterministic': False, 'domain': ['lan', 'wan'], 'id': 'a904cefbdc5c4d09a3032e0f8e3eb8bc', 'lfn2pfn_algorithm': 'cmstfc', 'protocols': [{'hostname': 'xrootd.phy.bris.ac.uk', 'scheme': 'davs', 'port': 1094, 'prefix': '/xrootd/cms/store/temp/', 'impl': 'rucio.rse.protocols.gfal.Default', 'domains': {'lan': {'read': 0, 'write': 0, 'delete': 0}, 'wan': {'read': 1, 'write': 1, 'delete': 1, 'third_party_copy_read': 1, 'third_party_copy_write': 1}}, 'extended_attributes': None}, {'hostname': 'xrootd.phy.bris.ac.uk', 'scheme': 'root', 'port': 1094, 'prefix': '//xrootd/cms/store/temp/', 'impl': 'rucio.rse.protocols.gfal.Default', 'domains': {'lan': {'read': 0, 'write': 0, 'delete': 0}, 'wan': {'read': 3, 'write': 0, 'delete': 0, 'third_party_copy_read': 3, 'third_party_copy_write': 0}}, 'extended_attributes': None}], 'qos_class': None, 'rse': 'T2_UK_SGrid_Bristol_Temp', 'rse_type': 'DISK', 'sign_url': None, 'staging_area': False, 'verify_checksum': True, 'volatile': False, 'read_protocol': 1, 'write_protocol': 1, 'delete_protocol': 1, 'third_party_copy_read_protocol': 1, 'third_party_copy_write_protocol': 1}.
    ```

    <details>
      <summary>Reproducible snippet [1]</summary>

      ```python
      # omit rucioClient initializing
      rse = 'T2_UK_SGrid_Bristol_Temp'
      rse_temp = f'{rse}_Temp'
      src_lfn = '/store/temp/user/tseethon.d6830fc3715ee01030105e83b81ff3068df7c8e0/tseethon/test-rucio/ruciotransfers-1/GenericTTbar/ruciotransfers-1/230707_101712/0000/output_951111.root'
      dst_lfn = '/store/user/rucio/tseethon/test-rucio/ruciotransfers-1/GenericTTbar/ruciotransfers-1/230707_101712/0000/output_95.root'
      src_did = f'user.tseethon:{src_lfn}'
      pfn = rucio.lfns2pfns(rse, [src_did], operation="third_party_copy_read", scheme='root')[src_did]
      fr = [{'scope': 'user.tseethon', 'name': dst_lfn, 'pfn': pfn, 'bytes': 630787, 'adler32': '8da5ff37'}]
      rucioClient.add_replicas(rse_temp, fr)
      ```
    </details>

- `T2_DE_DESY_Temp`: Got `RSEFileNameNotSupported` exception:

    ```
    RSEFileNameNotSupported: RSE does not support provided filename.
    Details: Invalid prefix: provided '/pnfs/desy.de/cms/tier2/temp', expected '/pnfs/desy.de/cms/tier2/store/temp'
    ```

    <details>
      <summary>Reproducible snippet [2]</summary>

      ```python
      # omit rucioClient initializing
      rse = 'T2_DE_DESY'
      rse_temp = f'{rse}_Temp'
      src_lfn = '/store/temp/user/tseethon.d6830fc3715ee01030105e83b81ff3068df7c8e0/tseethon/test-rucio/ruciotransfers-1/GenericTTbar/ruciotransfers-1/230707_101712/0000/output_95_test1.root'
      dst_lfn = '/store/user/rucio/tseethon/test-rucio/ruciotransfers-1/GenericTTbar/ruciotransfers-1/230707_101712/0000/output_95.root'
      src_did = f'user.tseethon:{src_lfn}'
      pfn = rucio.lfns2pfns(rse, [src_did], operation="third_party_copy_read", scheme='davs')[src_did]
      fr = [{'scope': 'user.tseethon', 'name': dst_lfn, 'pfn': pfn, 'bytes': 630787, 'adler32': '8da5ff37'}]
      rucioClient.add_replicas(rse_temp, fr)
      ```
    </details>

Note that I can access files with gfal command from the path returned by `lfns2pfns()` from both sites.

Is this misconfiguration on Rucio side? or am I misunderstanding something?

**Comment by novicecpp** [comment]
@ericvaandering  Could you please help us?

**Comment by ericvaandering** [comment]
For DESY, this is the definition of the RSE in Rucio: 
```
Protocols:
==========
  davs
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy_read": 1, "third_party_copy_write": 1}}'
    extended_attributes: None
    hostname: dcache-cms-webdav-wan.desy.de
    impl: rucio.rse.protocols.gfal.Default
    port: 2880
    prefix: /pnfs/desy.de/cms/tier2/store/temp
    scheme: davs
```
so you need /store/temp not temp. 


For Bristol them output of `rucio-admin rse info` shows that they don't allow writing over root.

**Comment by novicecpp** [comment]
For Bristol, there was no `davs` endpoint for temp\_RSE when I tested two months ago (`rucio.get_protocols('T2_UK_SGrid_Bristol')` only returned `root` protocol). Now it works fine. 

But for DESY, should both normal RSE and temp\_RSE have the same protocols?

`T2_DE_DESY` has `tfc`'s extended_attributes while `T2_DE_DESY_Temp` has not. 
`lfns2pfns()` with `T2_DE_DESY` will return `/temp` but not `/store/temp` and I cannot pass `T2_DE_DESY_Temp` to `lfns2pfns()` to get PFN because it will raise the exception `ReplicaNotFound: Replica not found Details: No row found for Details: No row found for scope: user.tseethon name: ...`

**Comment by ericvaandering** [comment]
Extended attributes are only needed for complex site layouts where a prefix is not sufficient. >90% of sites don't need extended attributes whatsoever. 

I'm not sure what the issue with no row for scope. Can you show me exactly what you're doing?

**Comment by novicecpp** [comment]
I want to register the replicas in Temp\_RSE with `add_replicas` function.

Here is the code snippet:

```python
rucioScope = 'user.tseethon'
sourceRSE = 'T2_DE_DESY'
destinationRSE = 'T2_CH_CERN'
sourceLFN = '/store/temp/user/tseethon.d6830fc3715ee01030105e83b81ff3068df7c8e0/tseethon/test-workflow/GenericTTbar/autotest-1690819125/230731_155847/0000/output_6_mock.root'
destinationLFN = '/store/user/rucio/tseethon/test-workflow/GenericTTbar/autotest-1690819125/230731_155847/0000/output_6_mock.root'

# resolve pfn
_, srcScheme, _, _ = find_matching_scheme(
  {"protocols": rucioClient.get_protocols(destinationRSE)},
  {"protocols": rucioClient.get_protocols(sourceRSE)},
  "third_party_copy_read",
  "third_party_copy_write",
)
did = f'{rucioScope}:{sourceLFN}'
sourcePFNMap = rucioClient.lfns2pfns(sourceRSE, [did], operation="third_party_copy_read", scheme=srcScheme)
pfn = sourcePFNMap[did]
# pfn here is:
# davs://dcache-cms-webdav-wan.desy.de:2880/pnfs/desy.de/cms/tier2/temp/user/tseethon.d6830fc3715ee01030105e83b81ff3068df7c8e0/tseethon/test-workflow/GenericTTbar/autotest-1690819125/230731_155847/0000/output_6_mock.root

# create xdict
xdict = {
  'scope': rucioScope,
  'pfn': pfn,
  'name': destinationLFN,
  'bytes': 633409,
  'adler32': '7272db59',
}

# register replica
sourceRSETemp = f'{sourceRSE}_Temp'
rucioClient.add_replicas(sourceRSETemp, [xdict])
```

If I change `sourceRSE` to `T2_DE_DESY_Temp`, `lfn2pfns()` will raise `ReplicaNotFound`.

**Comment by ericvaandering** [comment]
This does not work for me since find_matching_scheme is not defined and I don't know what it could be.

**Comment by ericvaandering** [comment]
OK, so if I just hard wire it to DAVS I can reproduce your error. This problems seems present on any non-deterministic RSE? However the code, says it should be OK (perhaps referring to deterministic RSEs). 

But in a sense, what you are trying to do doesn't actually make sense. You can write these files ANYWHERE on a non-deterministic RSE. It doesn't need to be prefix+(file part of did). It could just as easily be /store/temp/user/ewv/[UUID4]

So I'm not sure what to say. In some sense what you're trying to do doesn't make any sense.

**Comment by novicecpp** [comment]
Hi Eric,
Thanks for looking at it.

> OK, so if I just hard wire it to DAVS I can reproduce your error. This problems seems present on any non-deterministic RSE? However the code, says it should be OK (perhaps referring to deterministic RSEs).

Let cast the LFN path and find_matching_scheme aside.
Yes, `lfns2pfns()` does not work with **any** non-deterministic RSE.
CRAB does a workaround by passing deterministic RSE to function to get PFN, as shown in the snippet.
However, this workaround has a problem; for some sites, the non-deterministic RSE config is not 1-1 compared to the deterministic RSE of the same site, either out-of-sync or for other reasons that are out of our control.
I need to hardcode it in [our scripts](https://github.com/dmwm/CRABServer/blob/50a9f8aa9d8ae6f55034cc62e3b6a27870b2c522/src/python/ASO/Rucio/Actions/RegisterReplicas.py#L298-L300) to make it work.

If `lfns2pfns()` cannot be fixed to accept non-deterministic RSE, do you have any suggestion to avoid hardcodes like the above?

> But in a sense, what you are trying to do doesn't actually make sense. You can write these files ANYWHERE on a non-deterministic RSE. It doesn't need to be prefix+(file part of did). It could just as easily be /store/temp/user/ewv/[UUID4]

Am I correctly understanding that PFN is the required argument for `add_replicas()` to add new files from non-deterministic RSE?
Because of that, we need `lfns2pfns()` to resolve PFN for us.

**Comment by ericvaandering** [comment]
Right but by definition lfns2pfns cannot resolve a replica name for a non-deterministic RSE if the replica doesn't exist because the PFN and LFN have no relationship to each other.  (Yes, for non-deterministic the LFN and PFN are both required to add a replica.)

For the most general case, I guess you'd need to implement the logic given in the full CMS TFC. However, I suspect that in all cases for _Temp RSEs it would be possible just to concatenate the /store/temp/ LFN with the RSEs 'prefix' and this could be defined if it's not. 

Keep in mind we did this BECAUSE the final LFN (/store/user/rucio/USERNAME/...) does not match the PFNs needed at temp sites (/store/temp/user/USERNAME). Unless you have changed that plan.

**Comment by novicecpp** [comment]
Ah, I see. That makes sense. 

> Keep in mind we did this BECAUSE the final LFN (/store/user/rucio/USERNAME/...) does not match the PFNs needed at temp sites (/store/temp/user/USERNAME). Unless you have changed that plan.

Is this the correct way to do in the Rucio world? Do we have another way to make transfer?
The main goal is to transfer files from temp RSEs, where crab jobs write output files to the local temp area, to a single deterministic RSE specified by users.

**Comment by ericvaandering** [comment]
Right, but as I understood it originally, the files have to be written at the initial location with the users credentials. Subsequently they are managed with the Rucio credentials. So this hop through the Temp RSE is necessary (a place where the user can write, Rucio can read, and perhaps Rucio can delete as well).

**Comment by belforte** [comment]
I'd rather not introduce any change now. But am intrigued by the possibility to put a Rucio credential in the job wrapper and put the file directly in /store/user/rucio/USERNAME at the execution site. Of course /store/temp/user exists everywhere, but /store/user/rucio is a different story, even if technically possible there will be a deployment pain

**Comment by dynamic-entropy** [comment]
Hello @novicecpp 
Is this still a concern?

**Comment by novicecpp** [comment]
Not anymore. The https://github.com/dmwm/CMSRucio/pull/766 work perfectly.
Thanks. You can close the ticket.
