### ISSUE TITLE
Reduce load created by the CE scanner

### ISSUE THREAD

**Issue by ivmfnal** [dmwm/CMSRucio#579]

**Comment by ivmfnal** [comment]
One way to reduce the load on CE is to not compile the list of empty directories as part of CE scanning.
Instead, store the CE scanner should store complete list of files and directories found in the storage in the scratch area and then have a separate cron job compile the list of empty directories and make it available.

**Comment by dciangot** [comment]
@ivmfnal any update on this?

**Comment by ivmfnal** [comment]
It is coded but not yet in the production

**Comment by ivmfnal** [comment]
The new code is in production since 8/29/2023.
