### ISSUE TITLE
ConMon unmerged page fails for T2_US_Caltech

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#581]
From here, https://cms-talk.web.cern.ch/t/rucioconmon-website-broken/28522

The conmon page return an error for T2_US_Caltech, it seems to work for other sites.
https://cmsweb.cern.ch/rucioconmon/unmerged/show_rse?rse=T2_US_Caltech

@ivmfnal can you please take a look?

**Comment by amaltaro** [comment]
I was looking for this link to provide it to Justas as well. I am glad there is already a ticket reporting it, thanks Rahul!

**Comment by ivmfnal** [comment]
Fixed
