### ISSUE TITLE
Recreate CE pod with newest version of xrootd-client

### ISSUE THREAD

**Issue by ivmfnal** [dmwm/CMSRucio#595]
xrootd developers plan to release new version of xrootd client where the "[FATAL] TLS error: resource temporarily unavailable" is fixed early the week of 9/11/2023. See https://github.com/xrootd/xrootd/issues/2082.

Once the release is officially out, we will need to rebuild CE pod image to pick up the updated version and then test CE.

Here are some sites where the official version of xrdfs currently fails: T2_US_MIT, T2_BE_UCL, T2_US_UCSD, T2_US_Florida, T2_EE_Estonia, T2_US_Nebraska

**Comment by ivmfnal** [comment]
No need to restart the pod with the new image because the running pod was patched manually already.

**Comment by ericvaandering** [comment]
We should, at our convenience, to make sure the change takes

**Comment by klannon** [comment]
Marked as "Done" in project board but issues is still open.  Is that a mistake?

**Comment by ericvaandering** [comment]
Yup
