### ISSUE TITLE
Restrict update_replica state permission

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#615]
The update_replica permission should be restricted to only the root user.

Such a direct update to the state of a replica (such as to `Bad`) does not update the relevant tables and thus leads to inconsistencies.

**Comment by dciangot** [comment]
Isn't that used by the "rucio upload" method on the client? 
In that case this will also prevent users from uploading without the --register-after-upload flag.

**Comment by dynamic-entropy** [comment]
Hi @dciangot 
I will have to look a bit deeper into the code. Because at the moment `update_replica_state` is only allowed to admins. 
So, it makes no difference to users. 

https://github.com/dmwm/CMSRucio/blob/028498485e3712fdff26637fa4fcddd407def404/src/policy/CMSRucioPolicy/permission.py#L850

But I get your point, have you tried rucio upload as a non-admin? Does it work?

**Comment by dynamic-entropy** [comment]
I will let this remain as is. 
I am not sure of all stakeholders using the `update_replica` command.
