### ISSUE TITLE
Open usage listing permissions for all users

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#616]
Non-admin users can list usage for only their own accounts.

This creates issues when users from relevant groups want to list usage for service accounts. 
 e.g. `pdmv` personals waiting to check the usage of the `wmcore_pileup` account
 
 Option 1: Open listing usages for all users by all users
 Option 2: Define "control group" for service accounts with such permissions
 
 More suggestions are welcome. If not, I am inclined towards option 1.
 
 FYI @ericvaandering @dciangot

**Comment by dciangot** [comment]
I don't see any particular danger in adopting option 1.
