### ISSUE TITLE
Configure loadtests via storage.json

### ISSUE THREAD

**Issue by haozturk** [dmwm/CMSRucio#636]
In the last DM Ops meeting (25.10.2023) we discussed how we can reduce the number of steps to enable/disable load tests. Status quo is that sites contact site support and site support contacts DM ops to configure them. Stephan Lammel suggested to introduce a new field in storage json which will specify whether load tests should be enabled or disabled. Our periodic scripts should parse it and set the expected behavior accordingly. @dynamic-entropy what's the feasibility of this?

@Panos512 fyi

**Comment by dynamic-entropy** [comment]
Well, its slow (max 1 hr delay). 

Secondly, what's the problem with setting it using the rucio command line? 
Is it that hard to do 
`rucio-admin rse set-attribute loadtest=True` 
`rucio-admin rse set-attribute loadtest=False` ?

**Comment by haozturk** [comment]
1hr delay is acceptable IMO. It's not hard. The problem is that it's required to be done by DM Ops. Sites or site support should be able to configure them without having to open a ticket to us. We're trying to minimize the manual actions. Besides, there is probably more delay after site support opens a ticket for us. 

Which script is responsible to read storage.json?

**Comment by dynamic-entropy** [comment]
Well, site support can run the same command. 
I think I have said this before, they have the permission to do so.

**Comment by haozturk** [comment]
Site support prefers the solution I outlined in the body. Besides, with this in place, sites can configure them without even contacting site support. 

Also do they have permission for all rucio-admin commands or just loadtest attribute?

Also repeating my question: Is this the script responsible for what we're talking: `docker/CMSRucioClient/scripts/setRucioFromGitlab`?

**Comment by dynamic-entropy** [comment]
What is the rationale behind the preference?

Yes.

**Comment by haozturk** [comment]
As I said, to avoid running a command every time the config has to be changed and to avoid sites having to contact site support to change configs. 

Additionally, `Yes` is an answer to which question? Because if site support has permission for all `rucio-admin` commands, it's a problem.

**Comment by dynamic-entropy** [comment]
Sites themselves do not control whether load tests should be enabled or not. It is a central thing. 
Running a command is less effort than changing confit on git. 

For permissions granularity: 
https://github.com/dmwm/CMSRucio/issues/627

**Comment by haozturk** [comment]
@stlammel said that they prefer guiding sites such that sites can configure themselves. Stephan, can you please clarify your perspective? I don't understand why site support prefers to use DM Ops jira interface for such config changes while they can configure loadtests at the moment via rucio-admin. Said that, please see my perspective on `rucio-admin` below:

> For permissions granularity: https://github.com/dmwm/CMSRucio/issues/627

Do I understand correctly that currently site support has all admin privileges, but we're planning to manage privileges in a finer granularity within the context of https://github.com/dmwm/CMSRucio/issues/627 ? 

I think we shouldn't give them admin privileges until a finer granularity permission scheme is developed.

Rahul, is there any special reason behind you don't prefer to add this automatic sync to setRucioFromGitlab?

**Comment by stlammel** [comment]
I believe site support to configure Rucio for sites is the wrong approach, it just puts as in the middle. For Rucio changes that sites can't do on their own we connect them to transfer/data management Jira. Thus the proposal to let sites enable/disable LoadTest via storage.json as other Rucio settings (and via a simple mechanism they are used too already).
 - Stephan

**Comment by dynamic-entropy** [comment]
Having the config in site config mean:
- dmops will need edit permission in the gitlab
- or we will have to add an extra override attribute for this configuration too
This makes it too complex than required, for e.g. when this should not be synced from siteconf but everything else should, etc.

If sites prefer to configure it themselves, then I can open permission to edit this attribute as part of #627 for `rucio site admins`. 
Does that work for you?

**Comment by stlammel** [comment]
We can add the dmops egroup to SITECONF, that should be straight forward.  - Stephan

**Comment by dynamic-entropy** [comment]
Alright, in that case, we can add it to the GitLab sync script.

**Comment by dynamic-entropy** [comment]
@stlammel If we can settle on the `key-value`  pair we will use in the configuration. We do not need to add it to the storage.json now. But we can add incrementally, as and when a need to change for that RSE appears. 

Is `loadtest=True` and `loadtest=False` good enough?

**Comment by stlammel** [comment]
Hallo Rahul, @dynamic-entropy 
   loadtest=True/False sounds good to me.
   Do we have other settings we want to delegate to site admins?
   Is cms-comp-ops-transfer-team@cern.ch still the right e-group for dmops or is there a better one to use for SITECONF write access?
   Thanks,
 - Stephan

**Comment by dynamic-entropy** [comment]
Greedy deletion and reaper could be another candidate, if you wish. 

Yes, that egroup is good.

**Comment by dynamic-entropy** [comment]
We decided to keep the deletion capabilities to DM. I will create a PR withe just the loadtest conf then.

**Comment by stlammel** [comment]
Ok, thanks Rahul!   - Stephan
