### ISSUE TITLE
Setting policy to 'cms' causes policy package to revert to what's in rucio/rucio repository

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#650]
At least that's what it seems like.

To get the conveyor-receiver working I changed the permission/schema values in the config to "cms" from "generic" But it seems this has moved our policy package from what is is CMSRucio/src back to what is in rucio/rucio under cms.py

Having this set in the server config
```
[policy]
permission = generic
schema = generic
```
along with the policy package (As it is now) means everything is basically OK.

Changing generic to cms seems to ignore our policy package.

**Comment by dynamic-entropy** [comment]
Unable to reproduce. 
Seems like the correct permission module from the policy package is being used. 

Please reopen if you find otherwise.
