### ISSUE TITLE
Revisit probes: check_report_used_space (RSE Usage monitoring)

### ISSUE THREAD

**Issue by haozturk** [dmwm/CMSRucio#651]
RSE Usage monitoring is key for operations. There are 3 different monitoring doing this. 

1. Probes: 
    - [The code](https://github.com/rucio/probes/blob/528aaf376dfa3e46bed4ade5c80bfa436f89d40a/cms/check_report_used_space). The metrics are pushed to `Prometheus`
    - [The dashboard](https://monit-grafana.cern.ch/d/O7M3h-UMk/rucio-used-space-in-disk-and-tape?orgId=11&var-country=All&var-tier=T1&var-rse=All&var-source=rucio&var-bin=avg_over_time:rucio_report_used_space:1d)
2. Jhonatan's monitoring pushing data to `influxdb`
     - The code: I don't know where the code is located. The data is pushed to influxdb
     - [Dashboard](https://monit-grafana.cern.ch/d/WPDxqoL4z/rucioaccounts?orgId=11&var-RSE=T1_US_FNAL_Tape&var-AccountType=All&from=now-7d&to=now&viewPanel=9&var-AccountName=All&var-ArchivalAccount=All&var-diskserviceaccount=All )
3. Panos' monitoring pushing data to `opensearch`

These different monitorings have inconsistencies between them. We discussed the issue with @Panos512 . We agreed that we should centralize this monitoring in probes. Panos told me that he already has the code.  I think we need to decide which data source to use for this purpose: Prometheus, influxdb or opensearch. And then we can update the probes code. @ericvaandering @Panos512 What's your thoughts on this?

Relevant CMSTRANSF issue: https://its.cern.ch/jira/browse/CMSTRANSF-574

**Comment by Panos512** [comment]
I think there might be no need to maintain our custom scripts that push to influx and opensearch. This information can very easily come from probes, in fact it already does. This is a plot I cooked up using data in Prometheus (coming from the probe) https://monit-grafana.cern.ch/d/LNwXC8mSk/panos-all-around-test-dashboard?orgId=11&var-src_rse=All&var-dst_rse=All&var-bin=10m&from=now-1w&to=now&viewPanel=18 

We still need to get minfreespace in there but it should be trivial, I've made a WIP PR here https://github.com/rucio/probes/pull/120 

There is also the question of retention policy. I see data up to one month ago in prometheus. Is this good enough? @nikodemas might be able to shed some light here. :)

**Comment by nikodemas** [comment]
Yes @Panos512, `cmsmonitoring` data source has a retention policy of 1 month. However, the data is aggregated (`rucio_report_used_space` metric) on an hourly level, is saved for 1 year and can be reached on Grafana with the `cms-monitoring-agg-1h` data source and also aggregated on daily, weekly and monthly level, saved for 10 years, and can be reached on Grafana with the `cms-monitoring-agg` data source.

**Comment by ericvaandering** [comment]
Ah, so this is the one that is already being aggregated. Perfect. 

Most of the things we use probes for are "health" related and 30-90 days is plenty. But not for this obviously. 

We can check this probe too. There is probably no need for this metric to be generated more frequently than every 15-30 minutes.

**Comment by Panos512** [comment]
Merging https://github.com/rucio/probes/pull/123 will enable available space information to be pushed in Prometheus. We can then create the RSE usage monitoring dashboard based on them, to be followed in a DM ops JIra ticket: https://its.cern.ch/jira/browse/CMSTRANSF-574
