### ISSUE TITLE
Migrate Client image for CronJobs to Alma9

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#652]
Dockerfile: https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/Dockerfile

**Comment by d-ylee** [comment]
@ericvaandering Would the merged PR close this issue?

**Comment by dynamic-entropy** [comment]
Hi @d-ylee 
If you use these keywords in the PR, the linked issue is closed automatically.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

(if this is what you meant)
Cheers
