### ISSUE TITLE
[DEV] Migrate loadtest image to Alma9

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#653]
Dockerfile: https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/Dockerfile.loadtest

Depends on #652 unless we separate them out

**Comment by haozturk** [comment]
Hi @d-ylee I'm trying to build the new client image you've updated via [1] and I do get this error
```
STEP 20/32: COPY scripts /scripts
Error: building at STEP "COPY scripts /scripts": checking on sources under "/home/haozturk/load-test-image-upgrade": copier: stat: "/scripts": no such file or directory
```
Have you tried to build this image? The directories that's required to build this image are in this folder [2] and we're trying to copy them before pulling them. Am I missing something?


[1] https://github.com/dmwm/CMSRucio/pull/714 
[2] https://github.com/dmwm/CMSRucio/tree/master/docker/CMSRucioClient

**Comment by haozturk** [comment]
Ah yes, indeed I was using the wrong context, thanks Dennis
