### ISSUE TITLE
Add a description of Rucio trace generation to Rucio instructions

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#662]

**Comment by yuyiguo** [comment]
**How the Rucio trace works**
The Rucio trace GitHub repo is at https://github.com/dmwm/rucio-tracers .
We make traces from three AMQ sources: 

- WMArchive: /topic/cms.jobmon.wmarchive
- CMSSWPOP: /topic/cms.swpop
- xrootd: /topic/xrootd.cms.aaa.ng

Rucio trace server listens to these sources and produces traces using these messages, then sends the newly created to AMQ /topic/cms.rucio.tracer. This is consumed by the Rucio Kronos.

The tree sources each have different schemas and naming conversions are also different. So the server needs to map them. In addition, the server also creates Prometheus metrics and they are sent to monitoring.

**Comment by ericvaandering** [comment]
PR accepted

**Comment by ericvaandering** [comment]
https://gitlab.cern.ch/cmsdmops/Documentation/-/merge_requests/18 is the second part

**Comment by ericvaandering** [comment]
Was merged
