### ISSUE TITLE
Add a section for prometheus setup to operator instructions

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#664]
Maybe just link to what we have in rucio-flux

**Comment by ericvaandering** [comment]
https://github.com/dmwm/rucio-flux/tree/main/infrastructure/prometheus

**Comment by ericvaandering** [comment]
Added https://gitlab.cern.ch/cmsdmops/Documentation/-/merge_requests/23

**Comment by klannon** [comment]
@ericvaandering This is marked as done, but the issue is still open.  Should it be closed?
