### ISSUE TITLE
Document for users the ability to authorize with an OIDC token

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#668]
As we discussed in the meeting today, this should be part of the user documentation.

**Comment by dciangot** [comment]
This is in a nutshell the steps needed from user perspective:
```
source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
export RUCIO_HOME=/cvmfs/cms.cern.ch/rucio/oidc
export RUCIO_ACCOUNT=dciangot
rucio whoami
```

Note that is currently broken as per #685

**Comment by dciangot** [comment]
done, included here https://twiki.cern.ch/twiki/bin/view/CMS/TheRucioCLI

@cmoore24-24 pls take a look, and move/edit as needed

**Comment by dciangot** [comment]
Closing, @cmoore24-24 can re-open if any info are missing
