### ISSUE TITLE
[BUG] OIDC authN fails to contact the IAM server

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#685]
**Describe the bug**

**To Reproduce**

```
source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
export RUCIO_HOME=/cvmfs/cms.cern.ch/rucio/oidc
export RUCIO_ACCOUNT=dciangot
rucio whoami
```

**Expected behavior**

The client should redirect the request to cms-auth IAM to get the user token properly.

**Possible Solution**

I need to look at the auth-server log, it might be related to changes on the IAM side. Probably the OIDC client has been removed for some reason. 

**Related Issues**

It might relates to #684

**Assignees**

@dciangot

**Comment by ericvaandering** [comment]
From #684 (these are really the same issue):

Sync of IAM subjects is currently broken with pod failng with:

+ echo 'Syncing OIDC user identities'
+ ./syncaccount_oidc.py
Syncing OIDC user identities
Traceback (most recent call last):
  File "./syncaccount_oidc.py", line 101, in <module>
    token = response['access_token']
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./syncaccount_oidc.py", line 103, in <module>
    raise RuntimeError("ERROR oidc get token: {}".format(e))
RuntimeError: ERROR oidc get token: 'access_token'
