### ISSUE TITLE
[DEV] Update dashboards which use output of check_rule_counts

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#688]
https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=6
and
https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=40"

**Comment by haozturk** [comment]
I created a new dashboard for this probe: https://monit-grafana.cern.ch/d/d534a131-5970-4139-b700-3de5516f2127/wip-rucio-updated-probes?orgId=11&var-RuleState=All&var-RucioInstance=prod&var-Activity=All&var-OlderThanDays=1&from=now-7d&to=now 

There is a new PR to merged for all filters to work properly: https://github.com/rucio/probes/pull/130 

@amanrique1 @Panos512 @dynamic-entropy @flgomezc I'd appreciate your feedback on this dashboard.

**Comment by haozturk** [comment]
Yes! We just need to move it prod which will be handled at [1]

[1] https://its.cern.ch/jira/browse/CMSMONIT-603
