### ISSUE TITLE
Document how to do minor and major rucio upgrades and how to start/stop Rucio

### ISSUE THREAD

**Issue by haozturk** [dmwm/CMSRucio#693]
I basically documented what I learnt this month from Eric which are how to do minor and major rucio upgrades and how to start/stop Rucio:

- https://cmsdmops.docs.cern.ch/CMSRucio/Rucio%20maintenance/minor_version_upgrades/
- https://cmsdmops.docs.cern.ch/CMSRucio/Rucio%20maintenance/major_version_upgrades/
- https://cmsdmops.docs.cern.ch/CMSRucio/Rucio%20maintenance/start_stop_rucio/

It'd be helpful if you could review it @dynamic-entropy @ericvaandering I'm sure there are some missing parts and perhaps inaccurate parts well. I intend to continue documenting Rucio maintenance here as we go along.

**Comment by ericvaandering** [comment]
On the minor version upgrades, I would say then to look at the running pods, make sure they aren't crashing. Take a look at the logs of a couple of daemons, make sure they look OK. Look at the auth server and server logs to make sure they are generating Rucio tokens and are OK. Check the WebUI. Lastly, come back to the server logs 60 minutes later. By that point all tokens issued by the old version have expired, so you should still see things moving correctly.

For the major version, all the same checks. But also save the SQL commands from integration to be applied to production (we don't do alembic and the upgrade pod again if we can avoid it).

**Comment by haozturk** [comment]
Thanks @ericvaandering I included your comments in the docs [1]. Is there anything else left to put there at this stage?

[1] https://gitlab.cern.ch/cmsdmops/Documentation/-/commit/73eddbf5bce6b938803eb7b5d2cc3f2a981a2c32

**Comment by ericvaandering** [comment]
No I don't think so
