### ISSUE TITLE
Enable Fireflies

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#710]
### Feature Description

Fireflies are UDP packets identifying experiments and activities for data transfers

### Use Case

Having this information available allows to better understand what exactly is happening at the network level as well as makes it possible to correlate information about the data transfers with the information that network providers have on the network flows.

### Proposal

- [x] Verify activity JSON
- [x] Update rucio config

### Possible Solution

Config table modifications:
- Add to config table
```
[packet-marking]
enabled=True
exp_name=cms
```

**Comment by ericvaandering** [comment]
I did this with `rucio-admin`. It's in the database config
