### ISSUE TITLE
Bug: Dark file declaration step for rucio consistency checks fails with unkown database exception 

### ISSUE THREAD

**Issue by ArturAkh** [dmwm/CMSRucio#719]
### Bug Description

Dear CMS Rucio experts,

For some of the recent rucio consistency checks visible at:

https://cmsweb.cern.ch/rucioconmon/ce/index

The dark files declaration step fails. Examples for T1_DE_KIT_Tape:

https://cmsweb.cern.ch/rucioconmon/ce/show_rse?rse=T1_DE_KIT_Tape

Most recent of these:

https://cmsweb.cern.ch/rucioconmon/ce/show_run?rse=T1_DE_KIT_Tape&run=2024_02_08_08_52

Error message given:

"""
dark_action failed
error: rucio error: Database exception. Details: An unknown Database Exception has ocurred.
"""

It seems like for some sites, the same error occured but was fixed after a while. Examples for T1_DE_KIT_Disk:

https://cmsweb.cern.ch/rucioconmon/ce/show_rse?rse=T1_DE_KIT_Disk

A similar error happened on January 17th, but was fixed on January 30th.

Would you please have a look at this issue?

Thank you very much in advance!

Best regards,

Artur Gottmann

**Comment by dynamic-entropy** [comment]
I find this in the latest runs of CC; when marking `quarantined replicas` as part of  dark_actions
```
/usr/local/lib/python3.9/site-packages/rucio/core/quarantined_replica.py:69: 
SAWarning: Column 'CMS_RUCIO_PROD.quarantined_replicas.path' is marked as a member of the primary key for table
'CMS_RUCIO_PROD.quarantined_replicas', but has no Python-side or server-side default generator indicated, nor does it
indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not 
store NULL. Note that as of SQLAlchemy 1.1, 'autoincrement=True' must be indicated explicitly for composite 
(e.g. multicolumn) primary keys if AUTO_INCREMENT/SERIAL/IDENTITY behavior is expected for one of the columns
 in the primary key. CREATE TABLE statements are impacted by this change as well on most backends.
```

**Comment by dynamic-entropy** [comment]
As can be seen in the logs above; the error occurs when CC tries to `quarantine` a replica that already exists in the table.

**Comment by ericvaandering** [comment]
Closing the issue

**Comment by ArturAkh** [comment]
@dynamic-entropy, all,

Thanks a lot for taking care of this!

One question for my understanding: Is it then the responsibility of sites to remove the dark files in case of tape sites?

Cheers,

Artur

**Comment by ArturAkh** [comment]
Thanks a lot for the clarification, @dynamic-entropy! A clean up during the deletion campaigns once a year is totally fine, I would say.

In that case, I wonder though, why these files were not included in the past campaigns, though - at least some of these are pretty old, if looking at the list of LFN's.

In any case, having them included in the next deletion campaign is fully sufficient, so more frequent deletion is not required. I anyhow suspect that these are from the Phedex ---> Rucio transition time, or from our migration between old and new tape system, where we have migrated too much to be on the safe side :)


Thanks a lot :) Let's see how the EM evolves :)

Cheers,

Artur

**Comment by dynamic-entropy** [comment]
As I see in the database, they were only `quarantined` (rucio terminology for dark files) on `13/1/2024`.
Currently, I see `10862` replicas at KIT_Tape in this table.

**Comment by ArturAkh** [comment]
OK, thanks, I see. So let's wait then for the next deletion campaign :)
