### ISSUE TITLE
Bug: Wrong rule approval receipients

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#733]
### Bug Description

This comes from https://ggus.eu/index.php?mode=ticket_info&ticket_id=165427#update#5

A user created a rule with a `--ask-approval` flag with a multirse expression `tier=2`. 
As a result, the site admins of `T2_UR_BERJ` were notified/asked to approve the request, which of course they did not have permission to do.

What I am not sure about is whether the message is sent to just one of the possible site admins or all of them?

### Reproduction Steps

- Create a rule with multi-rse expression along with ask-approval

### Expected Behavior

Needs to be discussed. It's a tiny caveat but needs to find a proper resolution.
@drkovalskyi @haozturk 

### Possible Solution

1. Either disallow multi rse expressions with --ask-approval for nonauto-approve requests?
    - With the auto-approve in place, I am not sure why users are using this, maybe something to tell them about? Since in the end, the quota is still being consumed from central space. 
    - this would be easy to do
    
2. Or keep the possibility to create such an expression, but then the recipient for approvals should be transfer_ops
    - This could take some time to figure out perhaps but it is still something we should send upstream to the core rucio team

**Comment by rvaladao** [comment]
> What I am not sure about is whether the message is sent to just one of the possible site admins or all of them?

Both T2_BR_UERJ admins (wcarvalh and erevored) received the email notification asking for approval.

**Comment by dynamic-entropy** [comment]
Thank you @rvaladao that is helpful.
Additionally, another thing to look at is, say, if this went to all tier2 admins (as defined in the rse_expression).

**Comment by ericvaandering** [comment]
Expected behavior is that rules targeting multiple RSEs cannot be made with ask approval. I thought this had been the case in the past.

**Comment by kenbloom** [comment]
T2_US_Nebraska got this also...presumably it hit every T2 site.

**Comment by dynamic-entropy** [comment]
Hello, 
Thankyou Ken
Yup, eric is correct, in the past, this was restricted in core rucio. But we remove it with auto_approval since auto_approve should allow multi-rse expression.
So, now this is up to the experiments policy package.
