### ISSUE TITLE
Send logs to Timber MONIT Timber instance

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#741]
The logs are currently sent to our test instance https://os-cms.cern.ch

 

The shall be routed to MONIT Timber instances
- [x] Create ticket for monit to create a producer
- [x] Modify the output config to route to the new dest
    - Remember to change the index name

**Comment by ericvaandering** [comment]
Is this issue finished?

**Comment by dynamic-entropy** [comment]
Hello @ericvaandering , 
Can we move this to deferred, please? Will do it in Q2.

**Comment by dynamic-entropy** [comment]
@ericvaandering Logs are now available at https://monit-timberprivate.cern.ch/dashboards/goto/d87c0e35108561ca32a0829ae1330d6d?security_tenant=cmsrucio

Cheers

**Comment by haozturk** [comment]
I'm unauthorized to access this @dynamic-entropy can you please give me access?

**Comment by dynamic-entropy** [comment]
Everyone in `cms-rucio-dev` egroup should have access now. I can see the egroup changes have propagated.
Cheers
