### ISSUE TITLE
Enhancement: Allow versioned data tier for partial pileup data placement

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#744]
### Enhancement Description

Allow container names with numeric version suffixes e.g. `RAW-V1`, `GEN-SIM-V21`  to be registered under the 
`group.wmcore` scope. 

The current schema is defined here,

https://github.com/dmwm/CMSRucio/blob/3535027a0c6796d7c7cbcd2d4f736c7ba5773c42/src/policy/CMSRucioPolicy/schema.py#L57-L60

### Use Case

WM team wants to let rucio allow dataset names of the type `DATATIER-V1` to register partial pileup containers.

Each time a user requests a new fraction a custom name with such a suffix pattern is created, where the version is incremented per request. 

A gist explaining further details https://gist.github.com/amaltaro/b4f9bafc0b58c10092a0735c635538b5

FYI @ericvaandering

**Comment by amaltaro** [comment]
Thank you for creating this issue, Rahul.

It looks like changing the container regex from:
```
r'^/[a-zA-Z0-9\-_]{1,99}/[a-zA-Z0-9\.\-_]{1,199}/[A-Z\-]{1,50}$'
```
to
```
^/[a-zA-Z0-9\-_]{1,99}/[a-zA-Z0-9\.\-_]{1,199}/[A-Z0-9\-]{1,50}$
```
would be enough. Right? Note that we do not need to change anything in the `cms` scope, only in the `group.wmcore`.

Just so we can plan validation and upgrades on our side, do you think we could have such changes in Rucio Int this week? Or would you be able to give an ETA for this? @dynamic-entropy @ericvaandering

**Comment by amaltaro** [comment]
Sorry for being late, but I think it's worth it to mention that the length of this field might have to be corrected as well. This is the relevant change made in WMCore: https://github.com/dmwm/WMCore/pull/11930/files

and here I raised a concern of inconsistency: https://github.com/dmwm/WMCore/pull/11930#issuecomment-1999076515

To me, it looks like datatier can have up to 99 chars (either standalone or in the final dataset regex). @todor-ivanov could cross-check this information for us and make these consistency across systems (Rucio x DBS x WMCore).

**Comment by ericvaandering** [comment]
IIRC, there is also a limit on the total length of a dataset. And the sub part values were chosen to add up to that total length. But maybe my memory is not sharp for decisions made 15 years ago. 🤣

**Comment by dynamic-entropy** [comment]
I will reopen this until we finalise a consistent pattern and length. 
Cheers

**Comment by dynamic-entropy** [comment]
I was expecting more comments here. So what is the consensus? 
@todor-ivanov ?

**Comment by todor-ivanov** [comment]
Hi @dynamic-entropy as we just discussed we can safely take the 99 char length here and we will be fine. I think you may close this issue

**Comment by dynamic-entropy** [comment]
Thank you, Todor. 
This would make limits to,

```
CONTAINER length - 300
BLOCK length - 400
FILE length - 500 (unbounded by regex but by the DB schema). 
```

@ericvaandering I do not understand this if my above calculations are correct, https://github.com/dmwm/CMSRucio/blob/3535027a0c6796d7c7cbcd2d4f736c7ba5773c42/src/policy/CMSRucioPolicy/schema.py#L64
Can you have a look?

**Comment by dynamic-entropy** [comment]
Got it, I was not counting the `/` in the names.
