### ISSUE TITLE
Determine which information CMS should send to CTA/tape systems for grouping decisions

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#753]
This first issue is a requirements issue and certainly needs a discussion. There are some ideas in #323 but now we have technical constraints too, which is that we are supposed to supply 4 levels information to be used to make grouping decisions. 

https://indico.cern.ch/event/1353243/contributions/5812010/ is worth taking a look at too.

**Comment by ericvaandering** [comment]
Seems to me level 0 is likely data+era and MC+year. Level 1 may be data tier. 

@DAMason @drkovalskyi

**Comment by ericvaandering** [comment]
Let's not worry about what particular sites do. I assume Fermilab will still continue to create file families/storage classes in CTA and probably make the first level or two of data redundant with that. That's fine. The idea is that eventually CTA will use this information, especially the finer bits of it not just in which tapes some data is written to but how things are laid out on the tape. Writing data such that even if there are 10 datasets on a tape that all 10 are grouped together would be a large benefit for the read back. 

So we need to figure out our 4-levels even if the top ones are not useful to site which use file families (storage classes is the CTA term).

**Comment by drkovalskyi** [comment]
In this case, I would make level zero: Data or MC. The I would focus on the data tier for all types of data (level one). Any mass recall for reprocessing requires a specific data tier. Then, as level 3, for MC the most important part is the production campaign and for Data it's era, which may also include re-reco "campaign", but it's not systematic enough to rely on. I don't see anything worth considering for level 4.

**Comment by voetberg** [comment]
We can include campaign when its present level for 4, but otherwise not include a level 4.  Because its the lowest level, it wouldn't interfere with other levels, but would be beneficial when it is used.

**Comment by ericvaandering** [comment]
> In this case, I would make level zero: Data or MC. The I would focus on the data tier for all types of data (level one). Any mass recall for reprocessing requires a specific data tier. Then, as level 3, for MC the most important part is the production campaign and for Data its era, which may also include re-reco "campaign", but it's not systematic enough to rely on. I don't see anything worth considering for level 4.

I think you are missing the idea of file on tape positions which is where the lower levels would really come and could potentially make data access much faster and easier on the physical tape media. Take a look at https://indico.cern.ch/event/1353243/contributions/5812010/ especially slides 6 and 13. 

But I think it's pretty clear we need to have a chat and/or an O&C presentation before finalizing this. That doesn't mean the development can't start because we need to have a way to pull this information out of the DIDs before it can be put into these fields.

**Comment by drkovalskyi** [comment]
I have looked again at Julien's slide and I'm not sure what I'm missing. We can use the Tue time slot next week to have a chat if you want to.

**Comment by ericvaandering** [comment]
That would be great. I think. Assuming I am back from the eclipse. Do you want to make an indico dedicated to this?
Sent from a mobile device. Please excuse my brevity or transcription errors.

On Apr 4, 2024, at 2:08 PM, Dmytro Kovalskyi ***@***.***> wrote:

﻿

[EXTERNAL] – This message is from an external sender

I have looked again at Julien's slide and I'm not sure what I'm missing. We can use the Tue time slot next week to have a chat if you want to.

**Comment by drkovalskyi** [comment]
We can also find another time slot. Let's try to do it before CMS week. Wishing you good weather. The eclipse is an exceptional event.

**Comment by voetberg** [comment]
Hi, was there ever any movement on this? I have the basic outline of the plugin done, but I'm not sure where this discussion ended up.

**Comment by ericvaandering** [comment]
We have not. We should have a discussion though.

**Comment by klannon** [comment]
@ericvaandering Issue is marked as done in board but not closed.  Can you clarify?  Is the information that was determined documented somewhere?  (Last comment was from April 29 saying discussion is needed.)

**Comment by ericvaandering** [comment]
@klannon thanks for catching this. We had the discussion and made the decision, so now it's implementation and @voetberg says it's already pretty much done.
