### ISSUE TITLE
Feature: Don't allow rule creations against tape RSEs if a lifetime is provided

### ISSUE THREAD

**Issue by haozturk** [dmwm/CMSRucio#759]
### Feature Description

Rucio should reject rule creations if the RSE expression includes a tape RSE and there is a lifetime

### Use Case

This is an extra layer of protection against operator mistakes. Operators could mistakenly create rules with lifetime for tape RSEs in the current setup. This shouldn't be possible.

**Comment by dynamic-entropy** [comment]
Hello @amaltaro 
 I believe this should be already the case for all WM rules, kindly let us know if not.
Do you think we can go ahead with adding such a restriction for tape rules?

**Comment by amaltaro** [comment]
That is correct! WM does not set lifetime for Tape rules and I think it's a good idea to enforce it! Thanks

**Comment by dynamic-entropy** [comment]
Thankyou Alan
