### ISSUE TITLE
Enhancement: Bring Integration RSE configuration closer to prod

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#765]
### Enhancement Description

RSEs on rucio integration seem many years old; rendering most of them useless
Some examples of issues:
- Allow testing rucio schema and policy changes on int
   - T0 was not able to test L1Scout on int until this was moved to production
   
- Many RSEs on integration use gsiftp
   - We do not use it in production
   - It gave IT wrong idea that CMS is doing transfers with gridFTP
   

### Use Case

Add confidence in ad-hoc tests and make a base for building more testing infrastructure on the rucio integration server.

### Possible Solution

Modify and run cms rucio cron jobs on integration too.

**Comment by ericvaandering** [comment]
Should be part of a milestone to get integration and production as close as possible.
