### ISSUE TITLE
Bug: T2_TR_METU site status not getting updated in rucio

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#785]
### Bug Description

The site is unreachable and in downtime https://cmssst.web.cern.ch/siteStatus/detail.html?site=T2_TR_METU

However, the automatic updates have not happened for days now. 

```
  availability: 7
  availability_delete: True
  availability_read: True
  availability_write: True
```

**Comment by stlammel** [comment]
Hallo Rahul, @dynamic-entropy ,
   this is correct: sts15min status is LifeStaus and T2_TR_METU's LifeStatus is enabled.
The sts15min prod_status is ProductionStatus and is drain. (Similarly crab_status being disabled.) The site is in scheduled downtime, so did not have SiteReadiness error states that would put it into LifeStatus WaitingRoom.
   I'll try to add myself.
   'hope this helps,
                   cheers,  Stephan

**Comment by stlammel** [comment]
How do i add myself to the repository? Is it the "+" / "IMport repository"?
 - Stephan

**Comment by dynamic-entropy** [comment]
@stlammel 
So for the site status metric, we can assume that even for "Scheduled Downtime" the `status` field will be set to `disabled` and we do not need to change the below logic?
https://github.com/dmwm/CMSRucio/blob/1e83e3717a2ed3977d1560629a612ef653cbc899/docker/rucio_client/scripts/setSiteAvailability#L63-L64

Cheers

**Comment by stlammel** [comment]
Ok, i have ask Diego and Eric.

No, site status is independent of scheduled/unscheduled downtimes. The site status metrics specify/suggest if a site should be used during the coming day. The site may or may not be in downtime, i.e. provide no resources.
While a site is in scheduled downtime, it's counted as neutral (neither ok nor error) in SiteReadiness which means there is no status change that is based on SiteReadiness. (CRAB which is based on HC will still change but not ProdStatus or LifeStatus as they are based on SiteReadiness.) Confusing?
 - Stephan

**Comment by ericvaandering** [comment]
Let's take this to Mattermost ?

**Comment by dynamic-entropy** [comment]
@stlammel 
From your above comment, I understood that a downtime translates to "no automatic updates based on site-readiness". 
However, we (the rucio cronjob) will still need the status field to be disabled during downtime. 

So, what I am asking is, can we rely on automatic or manual updates of the field by site support?
Or do we need a different logic to set the site availability in rucio

**Comment by dynamic-entropy** [comment]
Most of the queue to METU has been consumed. 
The changes we made yesterday (setting availability write manually and skipping availability update from sts metric) have prevented further doomed submissions to the site. 

Closing this.
