### ISSUE TITLE
Bug: SAM files aren't automatically copied if a site is down

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#790]
### Bug Description

Site status depends on SAM files to be present at a desired location to perform various functional tests on a site.
We depend on the metrics generated by these tests to toggle the `availability_write` for the site. 

In a situation where a SAM file is lost/corrupted at a site, they are not recovered simply by marking them bad, since the conveyor will not submit jobs for sites that are marked as such.

This prevents the auto-recovery of these files and needs a manual copy by either site admin or us. 

@stlammel (Thanks to eric, I can tag you faster now :sweat_smile: )

### Possible Solution

Run a separate conveyor for load tests and SAM files, which is configured to submit transfers irrespective of the availability status of a site.

**Comment by dynamic-entropy** [comment]
Wouldn't it be better to let them happen always?

What are the cases when we would want load tests to be off?

**Comment by stlammel** [comment]
I was thinking during commissioning if this takes an extended time, you may not want all the errors of failed transfers.
If not/never needed, we shouldn't consider/provide it.
 - Stephan

**Comment by dynamic-entropy** [comment]
For that, we can turn them off manually by removing the `loadtest=true` attribute. 

Is having a separate metric more intelligent? or does someone need to change configs for that too?

**Comment by stlammel** [comment]
I was thinking one additional state beween usable/restricted and readonly/no-writes we discussed, i.e. no separate metric but an extra state in the new Rucio or Transfer Status metric (to decouple transfers from ProdStatus).
One could also interprete/make the 3rdt state readonly/no-writes-except-SAM/HC.
 - Stephan

**Comment by dynamic-entropy** [comment]
Okay, thank you, Stephan. 
Let's formalise the schema for the metric and protocols for each state that might require manual intervention. 

Cheers

**Comment by dynamic-entropy** [comment]
I seem to have made a hasty assessment initially. I made an effort last year to attempt transfers for SAM and HC files even when `avilability_write` is turned off for the site. They fall in the 'Functional Test' category; just like the loadtests. 
https://github.com/dmwm/rucio-flux/blob/594ac118ab5fd10f866c602484f04d6ea10b0288/apps/production/loadtest-rucio-daemons.yaml#L24-L27

The submission was stuck for a different reason. Which is the fact that when we declare files bad; the recovery request for it does not use the same activity 'Functional Test' which is exempted from respecting the `availability_write` flag. It instead uses the `Recovery` activity.

I do not have an immediate solution to this but will think and discuss it.

**Comment by dynamic-entropy** [comment]
I have added operator instructions to deal with these lost SAM files: https://cmsdmops.docs.cern.ch/Operators/SAM%20Datasets/

So when SAM files are lost, DM needs to refresh the rule in addition to declaring files bad.
That should be enough.

Will close this.
