### ISSUE TITLE
Bug: T2_AT_Vienna not configured from RSE info

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#799]
### Bug Description

```
[ewv@lxplus957 ~]$ rucio-admin rse info T2_AT_Vienna | grep CE
  CE_cfg.ce_disabled: True
  CE_cfg.max_dark_fraction: 0.02
```
but if we look at https://cmsweb.cern.ch/rucioconmon/ce/show_run?rse=T2_AT_Vienna&run=2024_05_14_05_02 we see Vienna is running and using a max dark fraction of 1% consistent with the defaults and https://github.com/dmwm/rucio-flux/blob/77b232a9641a816707752b8543c05eb94ee37a0a/apps/production/prod-consistency-jobs.yaml#L167

**Comment by ericvaandering** [comment]
Related to #248 and #649

**Comment by d-ylee** [comment]
@ericvaandering In `merge_config.py`, the expected `CONFIG_PREFIX` is `CE_config.`:
https://github.com/dmwm/cms_consistency/blob/76e7026a1918ac5fe894da1122defb8d25765128/site_cmp3/merge_config.py#L6

However, as you noted above, the attribute to disable consistency enforcement has `CE_cfg` as the prefix.

We probably should decide what prefix we want to actually use, and then update the scripts and the RSE attributes accordingly.

**Comment by ericvaandering** [comment]
Let's change the RSE attributes. Do you have the permissions?

**Comment by d-ylee** [comment]
I just tried to add the attribute, and I don't have permissions.

**Comment by d-ylee** [comment]
I added the correct attributes: `CE_config.ce_disabled: True` and `CE_config.max_dark_fraction: 0.02`. I also deleted the incorrect attributes.

After running the job, the job returned with `The CE for RSE is disabled. Stopping`. So I think this bug has been fixed.
