### ISSUE TITLE
Enhancement: Complete porting of remaining probes to SQLAlchemy syntax

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#812]
### Enhancement Description

Three of the probes in our dockerfile need to be modernised:
PRs for two already seem to exist, but might need a review before merging and deploying.

- [ ] `check_expired_locked_rules`: https://github.com/rucio/probes/pull/133
    - one more (can be closed in favour of above I guess): https://github.com/rucio/probes/pull/43

- [ ] `check_deletable_replicas`: Expired lock: https://github.com/rucio/probes/pull/46

- [ ] `check_obsolete_replicas` : Did not find PR for this

### Use Case

Fix them all!!!

-----
I take this statement back (might have mixed up with some other tests): https://github.com/dmwm/CMSRucio/blob/ced44859cb74ac436ea4d75333ae9abce41fbc6d/docker/rucio-probes/Dockerfile#L36

It's just one, reviewed the PR to suggest the necessary fix.

### Related Issues

https://github.com/rucio/probes/pull/89

**Comment by ericvaandering** [comment]
I've linked the various PRs to this issue. Aside from the one in probes, they are done (and the one in probes isn't needed, we pull from the issue).
