### ISSUE TITLE
Don't use GFAL2 by default except for object store stuff (e.g. RAL)

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#98]
@KatyEllis care to elaborate?

**Comment by KatyEllis** [comment]
Cedric and Mario both told me in the Rucio Coding Camp that the gfalv2 in the 'implementation' of each protocol should only be used in the case of object stores (e.g. the disk storage at RAL, or any other Ceph-based storage system). All other storage should work better with :
impl: rucio.rse.protocols.gfal.Default

**Comment by ericvaandering** [comment]
@ddavila0

**Comment by ericvaandering** [comment]
This is now done with https://github.com/dmwm/CMSRucio/pull/277
